### ISSUE TITLE
Request fails when using application/graphql with body parser

### ISSUE THREAD

**Issue by AJ1310** [graphql/express-graphql#10]
When sending a Content-Type : application/graphql with a query string the request fails.
If using body parser json or url encoded it says that i don't have a query string.
if used with text type application/graphql it gets stuck on parseBody.js in the line 119.

**Comment by philostler** [comment]
+1 I'm experiencing exactly the same issue as @AJ1310 describes

**Comment by Aweary** [comment]
+1 I'm seeing this same issue and I've traced the hang all the way down to the `raw-body` package used to parse the `HTTPIncomingRequest` object.

`raw-body` attaches event listeners to the passed stream, but the stream is not emitting any of those events.

@leebyron [Here's is a logged copy of the stream object](https://gist.github.com/Aweary/aac594b907e12a91c285) for the query `{ post { title } }`

**Comment by leebyron** [comment]
This is now fixed and will go out with the next release.

**Comment by joanrodriguez** [comment]
Are you sure this has been fixed? I'm running  `express-graphql 0.4.13` with `body-parser 1.15.0` and doing a POST with headers set to `Content-Type: application/graphql` I get 

```
{
  "errors": [
    {
      "message": "Must provide query string."
    }
  ]
} 
```

**Comment by joanrodriguez** [comment]
I solved my problem doing the following:

```
// configure app to use bodyParser()
// this will let us get the data from a POST
// exclusing the route to graphql
app.use(/\/((?!graphql).)*/, bodyParser.urlencoded({ extended: true }));
app.use(/\/((?!graphql).)*/, bodyParser.json());
```

**Comment by leebyron** [comment]
Yes this is fixed. However if you're also using body-parser, you must still ensure the output of body-parser is compatible with the express-graphql plugin. 

The recommended use is still to use the express-graphql middleware *before* using any kind of body parser middleware you may be using for other routes.

**Comment by AvraamMavridis** [comment]
I am experiencing the same issue using :

    "body-parser": "^1.17.2",
    "express": "^4.15.3",
    "express-graphql": "^0.6.


My server:

```
const schema = require('./schema');
const express = require('express');
const graphqlHTTP = require('express-graphql');
const cors = require('cors')
const bodyParser = require('body-parser');


const app = express();
app.use(cors());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use('/graphql', graphqlHTTP(req => {
  return ({
  schema,
  pretty: true,
  })
}));

const server = app.listen(9000, err => {
  if (err) { return err; }
  console.log(`GraphQL server running on http://localhost:${9000}/graphql`);
});
```


Request:

<img width="476" alt="screen shot 2017-08-06 at 11 30 16" src="https://user-images.githubusercontent.com/283690/29002082-b0239c50-7a9a-11e7-9f59-f338d27b78fc.png">


**Any help?**

**Comment by SyedAman** [comment]
@AvraamMavridis you got this to work? I got the same exact issue

**Comment by AvraamMavridis** [comment]
@SyedAman see https://stackoverflow.com/questions/45530623/graphql-must-provide-query-string

**Comment by dh94** [comment]
@AvraamMavridis @ghost   try adding 
```
app.use(bodyParser.text({ type: 'application/graphql' }));
```

fixed it for me

**Comment by eric-burel** [comment]
@dh94 can you confirm that this need to be called after `bodyParser.json()` ? I had some issues with Apollo Server 2 in a Meteor app and writing
```
app.use(bodyParser.json())
app.use(bodyParser.text({ type: 'application/graphql' }));
```
seemed to fix it.

**Comment by uassawa** [comment]
https://www.npmjs.com/package/body-parser-graphql

fixed it for me

**Comment by louisse66** [comment]
Hello,

I have this in my app.js: 

const express = require("express");
const bodyParser = require("body-parser");
const graphqlHttp = require("express-graphql").graphqlHTTP;
const { buildSchema } = require("graphql");

const app = express();

app.use(bodyParser.json());

app.use(
  "/myproject",
  graphqlHttp({
    schema: buildSchema(`
        type TypeQuery {
            events: [String!]!
        }
    
        type TypeMutation {
            createEvent(name: String): String
        }
    
        schema {  
            query: TypeQuery
            mutation: TypeMutation
        }
    `),
    rootValue: {
      events: () => {
        return ["Cats", "Sailing"];
      },
      createEvent: (args) => {
        const eventName = args.name;
        return eventName;
      },
    },
    graphql: true,
  })
);

app.listen(3000);

When I typed in browser 'http://localhost:3000/myproject' I getting this error"{"errors":[{"message":"Must provide query string."}]}"

I have this in my app.js

const express = require("express");
const bodyParser = require("body-parser");
const graphqlHttp = require("express-graphql").graphqlHTTP;
const { buildSchema } = require("graphql");

const app = express();

app.use(bodyParser.json());

app.use(
  "/myproject",
  graphqlHttp({
    schema: buildSchema(`
        type TypeQuery {
            events: [String!]!
        }
    
        type TypeMutation {
            createEvent(name: String): String
        }
    
        schema {  
            query: TypeQuery
            mutation: TypeMutation
        }
    `),
    rootValue: {
      events: () => {
        return ["Cats", "Sailing"];
      },
      createEvent: (args) => {
        const eventName = args.name;
        return eventName;
      },
    },
    graphql: true,
  })
);

app.listen(3000);

When I typed in browser 'http://localhost:3000/myproject' I getting this error:
{"errors":[{"message":"Must provide query string."}]}

What I am wrong? In my project only change I made was in app.js. I don't have a frontend.

 Thank you!

:)
