### ISSUE TITLE
Add middleware to transform req.query

### ISSUE THREAD

**Issue by zgababa** [graphql/express-graphql#102]
Hi ! 

I have a compressed query in req, and I want to decompress it before send to GraphiQL. Why this code doesn't work ? Is it possible ? 

```javascript
router.use("/debug", (req, res, next) => {
  const decompressed = lz.decompressFromEncodedURIComponent(req.query.query);
  req.query = {
    query : decompressed,
  };
  next();
}, require("express-graphql")({
  schema : graphqlRootSchema,
  graphiql : config.get("NODE_ENV") !== "production",
  pretty : true,
  formatError : format.fromGraphiql
}));
```

Thx !

**Comment by leebyron** [comment]
If you use http-compatible compression (deflate, gzip) then express-graphql's body parser will automatically deflate the compressed body.

If you're doing some custom compression technique, then you will need to create your own middleware to decompress the body before using the express-graphql middleware.
