### ISSUE TITLE
Support for an array of queries in a single request?

### ISSUE THREAD

**Issue by ryancole** [graphql/express-graphql#110]
What are your thoughts on adding support for multiple queries in a single http request? This is currently possible via additional express middle ware. Does this sound like something that would make sense as a first class feature in express-graphql?

This can be useful when using a per-request query batching tool like DataLoader.

**Comment by ryancole** [comment]
Looks like #100 is focusing on this, already.

**Comment by leebyron** [comment]
Closing in favor of #100
