### ISSUE TITLE
Response with form validation errors

### ISSUE THREAD

**Issue by xpepermint** [graphql/express-graphql#12]
Let's say you have a `<form>` which posts data to API server. The API server validates the input and returns JSON object. If the input is invalid (e.g. invalid email or email already exists in database) an error objects {errors: {email: "already exists"}} is returned. 
How do we handle and serve these kind of errors when using GraphQL? How and where should data validation be implemented (should that be part of my GraphQL code, maybe inside each resolve function)?

**Comment by leebyron** [comment]
This is a bit outside the scope of the express plugin, and there is a good discussion of input validation here: https://github.com/graphql/graphql-js/issues/44

To answer your question briefly, yes resolve functions are a great place to put this kind of validation and error detection logic.

**Comment by xpepermint** [comment]
@leebyron Thanks! That link helped and I managed to create a helper library https://github.com/xpepermint/graphql-type-factory.
