### ISSUE TITLE
Uploading files with a better real world example

### ISSUE THREAD

**Issue by jferrettiboke** [graphql/express-graphql#123]
I saw [this implementation](https://github.com/graphql/express-graphql/blob/master/src/__tests__/http-test.js#L711) with `multer` on tests. In my opinion, it is not a real world example. I will explain why.

On tests, we have a simple example with `multer` doing this.
1. Request.
2. Handling Multer middleware and validating a single file.
3. Handling GraphQL endpoint.
4. Handling  the specific `resolve` function.

What happen if you have to implement different types of validations in different points? In my opinion, a real world examples would be something like as following.
1. Request.
2. Handling GraphQL endpoint.
3. Handling  the specific `resolve` function.
4. Validating the file/files on the `resolve` function with Multer or another library through the context.

I mean uploading files post-request (not pre-request). Maybe with this approach, Multer does not work well. It is a middleware for Express.

Does this approach make sense? Is this possible to achieve with Multer? Or another library? Any kind of ideas to see this issue clearer?

Thanks in advance.

**Comment by leebyron** [comment]
You could certainly pass the `request` object as part of `context` and then do whatever you like with it in resolver functions.

Though I'm not sure I fully understand the problem you're addressing, however if you have some ideal code you'd like to work around file uploads that doesn't work due to a limitation in this library, please feel free to reopen with that so we can work on a specific fix.

**Comment by jferrettiboke** [comment]
Yup. I know, @leebyron. I can use the `request` through the `context`. I just wanted to open the issue to discuss a better way (a better real world example) and put it on the test cases to achieve uploading files with limitations depending of the resource and not a general uploading of files with no limitations and working in a middleware before the `graphql` endpoint.

What do you think about it? Has `multer` a function to upload the file based on the `request` and `response` without using `next`? What library is the best to achieve this?

I can make these tests cases and improving test cases adding tests with limitations for a specific resource on within the `graphql` endpoint. But first, let me know what you think about this. I think this would be very helpful for many people.
