### ISSUE TITLE
Hook for query request and json response

### ISSUE THREAD

**Issue by reggi** [graphql/express-graphql#125]
I'm in need of a hook that contains the request query and the json response for every request. The idea is I'd love to store all incoming requests and responses. Is this possible at this level rather than the schema?

**Comment by helfer** [comment]
@reggi I think you'd have to write an express middleware.

If using [Apollo Server](https://github.com/apollostack/apollo-server) is an option for you. It's very similar to express-graphql if you use it with express, but it's more configurable. What you want to do could be easily done with Apollo Server by adding some logging in the `formatResponse` function, which has access to both the query and the result, if you pass it in.

**Comment by leebyron** [comment]
You could use the new `extensions` function which will ship in the next major version, however related to #107 a custom middleware may be more appropriate.
