### ISSUE TITLE
[Question] Validate query depth 

### ISSUE THREAD

**Issue by sbondaryev** [graphql/express-graphql#126]
Is it possible to validate a query depth somehow ?
For example:

```
{node1 {node2 } }
```

is valid

```
{node1 {node2 {node3}}}
```

is not valid

**Comment by nodkz** [comment]
Try to find the answer here https://github.com/graphql/graphql-js (this is a more relevant place for your question. The most relevant place is StackOverflow 😉).

Docs about **graphql-js** can be found here http://graphql.org/graphql-js/
BUT New graphql site lost information about `resolve` method's arguments.
So on top level type (in your case `node1`) I would create such resolver:
```
  type: new GraphQLObjectType({
    name: 'node1'
    fields: {
      node2: ...
      ...
    }
  }),
  resolve: (source, args, context, info) => {
     console.log(info); // should return AST of your query

     // when you found solution how to calc depth just return `reject`
     const maxDepth = someHowTraverseAstFromInfoArgToObtainDepth(info);
     if (maxDepth >= 3) {
       return Promise.reject('Not so deep, baby ;)');
     }

     return {};
  }
```

**Comment by nodkz** [comment]
@leebyron or it can be solved via [validation](http://graphql.org/graphql-js/validation/)?

For me, validation is most uncovered part of GraphQL-JS.

**Comment by sbondaryev** [comment]
Ok thanks,
I just thought that it is could be done in `validationRules` of graphqlHTTP before schema resolving
@leebyron: could you please specify the place in the article? I can't find the info

**Comment by leebyron** [comment]
You could write a custom validation rule for this if you like, and provide it with the `validationRules`, or you could use your method of tracking the depth with info.

However I'd highly suggest not doing something like this. Field depth is a poor approximation of query complexity, and there may be plenty of reasonable cases in your type system where querying to a certain depth is desirable.
