### ISSUE TITLE
Expose underlying graphql promise

### ISSUE THREAD

**Issue by kastermester** [graphql/express-graphql#132]
Would it be possible to expose the underlying graphql promise?

I'm trying to wrap my entire request in a SQL database transaction, which I have had some trouble figuring out how to do.

**Comment by olivierandriessen** [comment]
@kastermester I've the same issue. I've chosen to implement it manually. Currently I'm trying something like this:

````
    return onBeforeExecuteFn(
                context,
                operationName
            ).then(() => {

                // Perform the execution, reporting any errors creating the context.
                try {
                    return execute(
                        schema,
                        documentAST,
                        rootValue,
                        context,
                        variables,
                        operationName
                    );
                } catch (contextError) {
                    // Return 400: Bad Request if any execution context errors exist.
                    response.statusCode = 400;
                    return {errors: [contextError]};
                }
            }).then(result => onAfterExecuteFn(
                result,
                context,
                operationName
            ).then(() => result));
````

That way you can start the transaction in before execute and pass the transaction via context to your resolvers. Then when based on whether errors are empty commit or rollback.

**Comment by leebyron** [comment]
Unfortunately there isn't really one promise to expose to hook this in the way you're looking for, if you take a look at the source it's more complex than that.

I'd suggest creating the relevant information and then providing it to your executor in the *context* field so as to decouple from the http middleware itself.
