### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by Magneticmagnum** [graphql/express-graphql#154]
From the original graphiql repo, it states that it is possible to have GraphiQL send an introspection query to the server to build the schema.  

Is there any way to do this with express-graphql?

I ask, because in my situation, we are wrapping a legacy data system using graphql-java in a java spring environment.  It seems redundant and difficult to re-schema the data again in javascript when it has already been done in java.  Without introspection, we may not end up using graphql in our stack.

Would anybody else have ideas?

**Comment by leebyron** [comment]
Yes! In fact express-graphql is totally unaware of introspection queries - it simply wires up http to graphql. GraphQL knows how to run queries, including introspection queries.

For example, try running the query `{ __schema { types { name } } }` in your GraphQL API, you should see the result of this (simple) introspection query. For a fully formed introspection query, you can often find examples exported by various GraphQL server libraries. For JavaScript, check out:

```js
var introspectionQuery = require('graphql').introspectionQuery;
```

That gives you the string query to perform enough introspection to understand an entire schema. The definition of which you can find defined at: https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js#L14

**Comment by leebyron** [comment]
GraphiQL uses introspection in order to produce a copy of the server's schema locally, which is how it builds the documentation explorer and provides all of it's features. If you're curious how that's working so you can use a similar technique for your own project, check out https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L460 - the `buildClientSchema` function converts the result of this introspection query into a GraphQL.js Schema instance you can use.

**Comment by chentsulin** [comment]
FYI, just release a package which wrap introspection queries into a simple function, make it easier:

```js
const fetchSchema = require('fetch-graphql-schema');

// Replace url to test your server implement introspection queries or not
fetchSchema('http://localhost:8080/graphql') 
  .then(schemaJSON => {
    /**
     * {
     *   "data": {
     *     "__schema": {
     *       "queryType": {
     *         "name": "Query"
     *          ....
     */
  });
```

https://github.com/chentsulin/fetch-graphql-schema

**Comment by Magneticmagnum** [comment]
Amazing! Thanks guys! This is exactly what I was looking for! I'm excited to implement this strategy :)
