### ISSUE TITLE
Hooking into the Express response object in the resolver

### ISSUE THREAD

**Issue by erikschlegel** [graphql/express-graphql#156]
How do I get access to the express response object within the `rootValue` resolver method?

i.e.
```
app.use('/api/messages', graphqlHTTP({
  schema: SpatialMessageSchema,
  rootValue: SpatialMessageResolver,
  graphiql: true,
}));
```

```myResolver(args, res){```

**Comment by erikschlegel** [comment]
Is the suggested approach with handling express resolvers to return a Promise?

**Comment by leebyron** [comment]
Hey Erik,

You can check out the example in https://github.com/graphql/express-graphql#providing-extensions which illustrates using the original response object

For your case of wanting to use `request` as the rootObject, you could do:

```js
app.use('/api/messages', graphqlHTTP(request => ({
  schema: SpatialMessageSchema,
  rootValue: request,
  graphiql: true,
})));
```

If you need to do some work before resolving the GraphQL request, then yes you can return a Promise. 

```js
app.use('/graphql', graphqlHTTP(request => {
  return doSomethingSlowThenPromise().then(() => ({
    schema: mySchema,
    graphiql: true
  }))
})
```

You can also always use middleware ahead of the GraphQL middleware:

```js
// some random middleware that takes a minute
app.use('/graphql', (req, res, next) => {
  doSomethingSlowThenCall(() => {
    // then continue
    next();
  })
});

app.use('/graphql', graphqlHTTP({...})
```
