### ISSUE TITLE
Error when doing HTTP post with variables

### ISSUE THREAD

**Issue by esakkikrishnan** [graphql/express-graphql#161]
### curl 
-X POST 
-H "Content-Type: application/json" 
-d '{"query":"{query($stockId: String!){stock(sc_id: $stockId){sc_id,isin,bse_id,nse_id}}}","variables":"{\"stockId\":\"123\"}"}'
"http://localhost:4000/graphql"

### Error:
{"errors":[{"message":"**Syntax Error GraphQL request (1:8) Expected Name, found $\n\n1:** {query($stockId: String!){stock(sc_id: $stockId){sc_id,isin,bse_id,nse_id}}}\n          ^\n","locations":[{"line":1,"column":8}]}]}

**Comment by nodkz** [comment]
Problem with your bash command. Try to escape $ characters by \$.

**Comment by esakkikrishnan** [comment]
This happens even when I do Http Post via POSTMAN

**Comment by nodkz** [comment]
For me works perfectly.

POST https://graphql-compose.herokuapp.com/user/
```
{"query": "query($id: MongoID!){  userById(_id: $id) {_id name }}","variables": "{\"id\": \"57bb44dd21d2befb7ca3f010\"}"}
```

Ah, you did not encode variables as string.

**Comment by esakkikrishnan** [comment]
Yours work fine
When I am tring to do the same in my Graphiql It gives Error. What could be the problem
### ERROR:
"message": "Variables must be provided as an Object where each property is a variable value. Perhaps look to see if an unparsed JSON string was provided."

I am using express-graphql
![rsz_screenshot_from_2016-11-16_16-14-52](https://cloud.githubusercontent.com/assets/9219264/20344366/7930d114-ac18-11e6-8089-422ed691377c.png)


@nodkz

**Comment by nodkz** [comment]
Can not imagine where is the problem.
BTW maybe `sc_id` in args has `Int` type but you provide a `String`.

Anyway, try to
- review your code again, check middlewares
- update all packages (if you have latest versions try to install previous). 
This issue tracker for fixing bugs in lib. But it seems that problem somewhere in your code.

**Comment by esakkikrishnan** [comment]
sc_id is String,
But any way closing this issue.
Since its working for other people

**Comment by esakkikrishnan** [comment]
The issue was due to out of date package,
Thanks for the help @nodkz
