### ISSUE TITLE
Resolver question

### ISSUE THREAD

**Issue by plm75** [graphql/express-graphql#169]
Hello, 
I hope it's ok to ask a question here.

Assuming the following schema:

    type Person {
      _id: String
      firstName: String
      lastName: String
      friends: [Person]
    }

    type Query {
      person(_id: Int): Person
    }

I have the following resolvers:

    var remoteResolvers = {
      person: (args) => { return getRemotePersonById(args._id) }
    }
    function getRemotePersonById(_id) {
      console.log("getRemotePersonById " + _id);
      return new Promise((resolve, reject) => {
        Persons.findOne({ _id: _id }, (err, person) => {
          if (err) {
            return reject(err)
          }
          resolve(person)
        })
      })
    }

What I don't get is how to resolve the `friends` property ?

I tried adding `person.friends = person.friends.map(getRemotePersonById)` just before the resolve, but that goes into a loop ...

Thanks

Patrick

**Comment by sibelius** [comment]
@plm75 ask this question on stackoverflow or on graphql.slack.com
