### ISSUE TITLE
Configure limit of request body

### ISSUE THREAD

**Issue by roadhump** [graphql/express-graphql#181]
There is a hardcoded limit of request body (100 kb) https://github.com/graphql/express-graphql/blob/master/src/parseBody.js#L112 . I wonder if there is a reason of it and why it can't be configured. I want to use graphql mutations to upload files as base64-encoded strings (user generates pictures on frontend), but now I can't do it because of this limit.

It would be nice to have possibility to set this limit with middleware configuration.

**Comment by juniorplenty** [comment]
+1, exact same use case cc @marcolz

**Comment by chentsulin** [comment]
https://github.com/graphql/express-graphql/pull/72

**Comment by asiandrummer** [comment]
As suggested in #72, we recommend enabling this in prior to middle-wares to be more decoupled and modular.
