### ISSUE TITLE
[RFC] Allow a function for the context

### ISSUE THREAD

**Issue by arunoda** [graphql/express-graphql#187]
If we don't set a context, express-graphql set the http request object as the context. If we provide a context explicitly, there's no way we could access the HTTP `request` object inside a `resolve` function.

So, here's my suggestion. We could pass a function for the `context`. It's a mapper and it receives the request object as the first argument.

See:

```js
app.use('/graphql', expressGraphql({
  schema,
  graphiql: true,
  context (req) {
    return {
      user: req.user,
      db: appInfo.db
    }
  }
}))
```

May be this is a breaking change if someone already passing a function for `context`. If so, we could do this with a different field like `contextMapper`.

**Comment by nodkz** [comment]
@arunoda, right now you may do it in such way:
```js
app.use('/graphql', expressGraphql((req) => ({
  schema,
  graphiql: false
  context: {
    user: req.user,
    db: appInfo.db
  }
})));
```

**Comment by arunoda** [comment]
Thanks @nodkz.
That's pretty cool. I totally miss this part in the README: https://github.com/graphql/express-graphql#providing-extensions

**Comment by venkat4541** [comment]
Where is the context object used? And how? Trying to understand a use case.

**Comment by longvd89** [comment]
context is object , can allow context with a function
