### ISSUE TITLE
rootValue: request.session,

### ISSUE THREAD

**Issue by spyalert01** [graphql/express-graphql#19]
Hi,

app.use('/graphql', graphqlHTTP(request => ({
  schema: MySessionAwareGraphQLSchema,
  rootValue: request.session,
  graphiql: true
})));

How do I access the rootValue at schema.js?

**Comment by leebyron** [comment]
```js
new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve(parentValue, {}, { rootValue }) {
        // rootValue has session
      }
    }
  }
})
```

**Comment by leebyron** [comment]
Just added to readme in ee2def05ccd197539daa3b956b5dc29cc0997c72 thanks for the feedback!

**Comment by spyalert01** [comment]
hi @leebyron 
http://prntscr.com/8mescq < - This part I've done it it at server.js,  so I don't have to do it again at schema.js right?

**Comment by spyalert01** [comment]
hi @leebyron 
This solution is good. Is there anyway that we canw write in schema, when schema is loaded, irregardless which query / mutation is fired, we already have the rootValue. 
With that, we don't have to declare rootValue at every resolve.

I am seeing this should be easily accessible value similar to session in php.
