### ISSUE TITLE
Correct mime-type for JSON?

### ISSUE THREAD

**Issue by SimonDegraeve** [graphql/express-graphql#2]
I noticed the middleware returns JSON with `text/json` mime-type. Any reason why it doesn't return `application/json`? 
I know there is a debate about that for a long time in the community but I thought `application/json` became the norm.

**Comment by SimonDegraeve** [comment]
I mean I don't really mind, just curious since I am working on a [hapi](http://hapijs.com/) version of a GraphQL server, I don't like to blindly transform someone else work.
See [hapi-graphql](https://github.com/SimonDegraeve/hapi-graphql).

**Comment by fson** [comment]
@SimonDegraeve I believe that's by mistake, as the accepted content-type for the request body is `application/json` (https://github.com/graphql/express-graphql/blob/34c14410b2879355e192462bdd159df884c28537/src/parseBody.js#L37).

**Comment by SimonDegraeve** [comment]
Indeed, that would make sense... 
Do you have any feedback on the Hapi port?

**Comment by leebyron** [comment]
Thanks for finding this! Indeed it's a bug. application/json is intended
