### ISSUE TITLE
Need to inject network layer in Relay to work with session

### ISSUE THREAD

**Issue by benoitguigal** [graphql/express-graphql#20]
By default Relay does not send any cookie and so express-graphql middleware won't work with session. We need to explicitly configure the default network layer with this piece of code in the app entry point before calling `ReactDOM.render`: 
```
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://localhost:3000/graphql', {
    credentials: 'same-origin',
  })
);
```
It would be great to document this somewhere because for the moment it seems that session can work out of the box with GraphQL.

**Comment by leebyron** [comment]
Closing this since this seems like an issue with [Relay's](https://github.com/facebook/relay) network layer or documentation and not a problem with express-graphql. 

Please reopen and clarify if there is something amiss with express-graphql that I have missed.
