### ISSUE TITLE
Use own GraphQLScalarType functions will not be called

### ISSUE THREAD

**Issue by fasibio** [graphql/express-graphql#205]
Hi, 
I'm try to use an own GraphQLScalarType.... 
I use `makeExecutableSchema `from `graphql-tools`
First I set my new ScalarType 
```
import {GraphQLScalarType} from 'graphql
const myOwnScalarType = new GraphQLScalarType({
  name: 'myOwnScalarType ',
  description: 'my Own ScalarType ',
  parseValue: (value) => {
    console.log('parseValue', value)
    return 'NO DATA' // value from the client
  },
  serialize: (value) => {
    console.log('serialize', value)
    return 'NO DATA'// value sent to the client
  },
  parseLiteral: (ast) => {
    console.log('parseLiteral', ast)
    return 'NO DATA'
  },
})
```
Now i Add a new Object: 
```
const resolverFunctions = {
    myOwnScalarType: myOwnScalarType,
  }
```
and generate a Schema
`schemaStr = 'scalar myOwnScalarType  .... type someType { value : myOwnScalarType   }'
`
`const schema = makeExecutableSchema({typeDefs: schemaStr, resolvers: resolverFunctions})`
```
app.use(uri, graphqlHTTP({
    schema: schema,
    rootValue: root,
    graphiql: showGraphiql,

  }))
```
It work fine... 
Graphiql show me the new Type and the Description...
But if i ask for the field value the three Function (parseValue, serialize, parseLiteral)  will not be called... 
Do you know what I am doing wrong? 
Where I have to add the ScalarType too? (to rootValue ?? how? )

Thank you for your help. 
Best Regard
fasibio

**Comment by soneymathew** [comment]
Works for me. See this launchpad for a working example with your use case.
https://launchpad.graphql.com/4rrr9zv3x9

Is it possible that you missed to include `scalar myOwnScalarType` into your schema ?

**Comment by IvanGoncharov** [comment]
@fasibio Sorry, for the late response.

> I use makeExecutableSchemafrom graphql-tools

This package is responsible only for exposing your GraphQL server over HTTP.
If you have problems with your schema you should report it to `graphql-tools`.
