### ISSUE TITLE
IE 11 graphiql "Promise undefined"

### ISSUE THREAD

**Issue by raix** [graphql/express-graphql#210]
Due to the lack of support of Promise the graphiql ui breaks on IE11

Possible solution could be to add a polyfill just before the fetch polyfill in https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js#L65

**Comment by IvanGoncharov** [comment]
Fixed in 5a082b2a1d02aadb1aa5a284e61f03aaf7fc37de 🎉 
I'm working on a new patch release that will include this fix.
