### ISSUE TITLE
Graphiql default query

### ISSUE THREAD

**Issue by alewisohn** [graphql/express-graphql#211]
Is it possible to set the `defaultQuery` displayed by GraphiQL, short of setting up GraphiQL manually? I looked through the code and documentation, but was unable to find anything.

**Comment by wincent** [comment]
The default query is defined in GraphiQL ([here](https://github.com/graphql/graphiql/blob/fedbc6130939c1e34b29d23257aed7e858bfca0b/src/components/GraphiQL.js#L903-L931)) but you could override it if you passed in a new query [here](https://github.com/graphql/express-graphql/blob/5ef8167f370acb22e2c651099b17b1dc8b5d8b51/src/renderGraphiQL.js#L33) using  express-graphql's `renderGraphiQL`.

Note that out of the box, you don't actually call `renderGraphiQL` directly; express-graphql does that, and I don't think that call can currently be overridden. It's fairly easy, though, to expose GraphiQL via `renderGraphiQL` on a specific endpoint in an Express app, so my advice would be to do that.

**Comment by lightsprint09** [comment]
Wouldn't  it be better to expose a configuration parameter called `graphiqlConfiguration` which takes the [official GraphiQL config](https://github.com/graphql/graphiql#usage) every knows.
