### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by mikhail-riabokon** [graphql/express-graphql#22]
I was working this graphql and express and reach the moment than I can not hold all fields definitions in schema.js, so I tried to create the folder structure for this case. Which you can reach by [link](https://github.com/mikhail-riabokon/express_graphql_folder_structure). 
I would be glad to discuss this question. Thank you.

**Comment by wincent** [comment]
Thanks for sharing! While throwing everything in a single `schema.js` file is a great way to get started, it's true that it becomes unwieldy as the schema grows. You example definitely goes a long way towards imposing order.

Have you tried discussing this with other people on the [Slack channel](https://graphql-slack.herokuapp.com/)? I expect that others are probably exploring this question just like you are, and it would be interesting to share opinions.

**Comment by mikhail-riabokon** [comment]
@wincent I did not discuss this on the Slack, but it's good idea. Thank you.

**Comment by sulliwane** [comment]
I found this quite natural: https://github.com/mrblueblue/graphql-express-sqlite/tree/master/schema

**Comment by mikhail-riabokon** [comment]
@sulliwane what if you have more complex schema?

**Comment by xpepermint** [comment]
I'm satisfied with this:
<img width="252" alt="screen shot 2015-11-15 at 6 38 45 pm" src="https://cloud.githubusercontent.com/assets/174279/11170017/3373dc6e-8bc8-11e5-917e-8559d8264689.png">
I call schema with `require('./schema')`.

**Comment by mikhail-riabokon** [comment]
For example you have next query, which can grow up in future. Will you write all queries in one query file?
```
query {
 viewer {
  users (first: 10) {
   name,
   address {
    street,
    building,
    neighbors {
     firstName,
     lastName
    }
   }
  } 
 }
}
```

**Comment by xpepermint** [comment]
@mikhail-riabokon I create a file for each query that queries the database.

**Comment by mikhail-riabokon** [comment]
@xpepermint your variant is better than mine. Thank you. But I use not only one file for queries.

```
-- mutations
----- .......
-- types
----- ....
-- queries
----- root.js
----- queries
--------- queryField
------------ index.js
------------ ....
--------- ......
```
It make's queries more structured, and it's really help me with "queries mess".

**Comment by mikhail-riabokon** [comment]
I update [example](https://github.com/mikhail-riabokon/express_graphql_folder_structure) for better understanding.

**Comment by leebyron** [comment]
Sorry for my misunderstanding, is there a question or issue raised here? I'm not sure what you would like from me or this repo.

**Comment by leebyron** [comment]
My personal opinion is that splitting large schema up across many files is a good idea and something I would encourage. 

The reason the example in this repo builds a schema in a single file is because it is quite small and I wanted to keep the example simple.

**Comment by mikhail-riabokon** [comment]
@leebyron Actually I have asked about folder structure because it's hard to keep everything in one file. That's why we have discussed that, and @xpepermint gave good example and I have updated my, with more than "one level" of queries. So for now, I think this question can be closed, if you do not have any suggestions. Thank you.

**Comment by leebyron** [comment]
Okay great.

**Comment by ahelord** [comment]
@xpepermint hello how do you do to join the queries in a single object "GraphQLObjectType"

**Comment by xpepermint** [comment]
@ahelord Just use the usual `require` commands and make sure you set `fields: () => ({})` (a method that returns fields object).

**Comment by ahelord** [comment]
@xpepermint I'm sorry, do not ask well.

How do you assemble all the graphql query files in another file to parse the object

**Comment by ahelord** [comment]
@mykhailo-riabokon hi

you could have this project 

https://github.com/mykhailo-riabokon/express_graphql_folder_structure 

run with Express
