### ISSUE TITLE
JSON error when not passing any value in Query Variable of GraphiQL

### ISSUE THREAD

**Issue by rishirajgarg** [graphql/express-graphql#233]
JSON error when not passing any value in Query Variable of GraphiQL - 'Variables are invalid JSON'.
This should not be  mandatory for a user to provide a JSOn value in the Query variable .

express-graphql : 6.2.0

**Comment by asiandrummer** [comment]
Closing since the issue's been resolved with the commit referenced. Thanks for the contribution!
