### ISSUE TITLE
Could you add an example of how to do a Relay-style mutation?

### ISSUE THREAD

**Issue by nickretallack** [graphql/express-graphql#26]
In Relay you have to pass a complex "input" type into the query.  I'm not sure how to use the variables parameter to accomplish this.

**Comment by leebyron** [comment]
the variables editor should help you type the required JSON, usually that looks something like:

```js
{
  "simpleVariable": "abc",
  "complexVariable": {
    "input": {
      "key": "value"
    }
  }
}
```
