### ISSUE TITLE
Can we use this plugin with Hapi?

### ISSUE THREAD

**Issue by THPubs** [graphql/express-graphql#265]
Is it possible to use this with Hapijs? Anyone already done that?

**Comment by stubailo** [comment]
No, but you can use `graphql-server-hapi`: http://dev.apollodata.com/tools/graphql-server/index.html

**Comment by wincent** [comment]
There isn't much in here that is express-specific, but some work would have to be done to make it work with Hapi, Koa etc (see https://github.com/graphql/express-graphql/issues/200). The `graphql-server-hapi` package that @stubailo mentions is a good option that works today.

Going to close this seeing as we already have #200 to track broader compatibility. Thanks for posting the issue @THPubs!

**Comment by THPubs** [comment]
@stubailo @wincent Thanks guys! I will have a look at that project :smile:
