### ISSUE TITLE
Variable value for `where` becomes null

### ISSUE THREAD

**Issue by pre** [graphql/express-graphql#286]
If this issue doesn't belong to the express-graphql project, I am grateful if you could point me in the right direction. Thanks! I already tried to report this issue at graphql-sequelize https://github.com/mickhansen/graphql-sequelize/issues/468 :)

**

Query variables with array values do not seem to work. The same query works when the array values are passed directly in the query. However, if the array values are passed using query variables, the resolver just sees `null`. 

The following query loses the variable value of `$nicks` which becomes `null` in the resolver:

```graphql
query Users($nicks:[String!]) {
  users(where: {nick: {
    	in: $nicks} }) {
    id
    lastname 
    firstname    
  }
}

variables:
{"nicks": ["Carrie", "Tim"]}
```

The query works, when I pass the values directly in the query without using variables: 
```graphql
query Users($nicks:[String!]) {
  users(where: {nick: {
    	in: ['This', 'Works']} }) {
    id
    lastname 
    firstname    
  }
}
```

The debug route looks like this:
```javascript
users: {
  type: new GraphQLList(userType),
  args: defaultListArgs(),
  resolve:  (root, args) => {
          console.log("!!!!!!!!!! root", root);
          console.log("!!!!!!!!!! args", args);
        }
  })
}
```

And the debugging output looks like:
```
!!!!!!!!!! root undefined
!!!!!!!!!! args { where: { nick: { in: null } } }
```

It doesn't matter whether I pass the array as `in: [$nicks]` or `in: $nicks`, the resulting value is always null (either `null` or `[Object]` where `Object` is `null` when looked into). 

I have spent quite some time trying to figure out this, so any tips about the direction where to debug further or fix this, would be welcome.

**Comment by pre** [comment]
I found the root cause, and it's in graphql-sequelise. This issue is irrelevant to express-graphql project.

**Comment by wincent** [comment]
> I found the root cause, and it's in graphql-sequelise.

Thanks for closing the loop with us @pre!
