### ISSUE TITLE
Firefox with Relay opens GraphiQL instead of process query

### ISSUE THREAD

**Issue by vslinko** [graphql/express-graphql#29]
I found a function which is making decision about GraphiQL:
```js
/**
 * Helper function to determine if GraphiQL can be displayed.
 */
function canDisplayGraphiQL(request: Request, data: Object): boolean {
  // If `raw` exists, GraphiQL mode is not enabled.
  var raw = request.query.raw !== undefined || data.raw !== undefined;
  // Allowed to show GraphiQL if not requested as raw and this request
  // prefers HTML over JSON.
  return !raw && request.accepts([ 'json', 'html' ]) === 'html';
}
```

Requests that Relay send aren't "raw". BTW what is "raw"?
Firefox prefers HTML.

**Comment by wincent** [comment]
Great catch. Thanks for reporting.

I can repro this in Firefox (41.0.2). It is sending an `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8` header, unlike, say, Chrome, which is sending `Accept: */*`.

I think we can fix this on the Relay side, so I think we can close this one. I'll make sure a link to my Relay PR shows up here.

**Comment by wincent** [comment]
I'm going to close this one in favor of that Relay pull request. Feel free to comment again if you have anything to add, and thanks once again for reporting the issue.
