### ISSUE TITLE
Graphiql 0.10.2

### ISSUE THREAD

**Issue by asaf-romano** [graphql/express-graphql#298]
Hi,

Is it possible to use this library with the latest version of graphiql (0.10.2)?

**Comment by asiandrummer** [comment]
@asaf-romano yup - just updated to 3cdcd5621fcfe22b5ce493d7e9e6516e68240137 ;) did a quick testing against GraphiQL example app and it worked well.

**Comment by asaf-romano** [comment]
Thanks much!
