### ISSUE TITLE
GraphQL Peer-dependency not found

### ISSUE THREAD

**Issue by hansemannn** [graphql/express-graphql#308]
When using `npm install --save express-graphql`, I receive: 
```
├── express-graphql@0.6.5  (git+https://github.com/graphql/express-graphql.git#6dc89f2727146ad5129904ce1fbad79bd59c22f5)
└── UNMET DEPENDENCY graphql@^0.9.6

npm WARN express-graphql@0.6.5 requires a peer of graphql@^0.9.6 but none was installed.
```
Even trying to add `"graphql": "^0.9.6"` manually does not help, clearing the cache doesn't as well. Any advise?

**Comment by arxpoetica** [comment]
Similar problem with `yarn add express-graphql`:

```
warning "express-graphql@0.6.5" has incorrect peer dependency "graphql@^0.9.6".
```

**Comment by plusz** [comment]
Why don't you change dependency version in your package.json
from "graphql": "^0.9.6"  to "graphql": "^0.10.0"

**Comment by wincent** [comment]
As @plusz says, the peer dependency is now ^0.10.0, so please give that a shot and let us know if you have any further problems.
