### ISSUE TITLE
Missing support for custom default field resolver

### ISSUE THREAD

**Issue by mhagmajer** [graphql/express-graphql#331]
API for this package doesn't allow providing custom default field resolvers.

See more at: https://github.com/graphql/graphql-js/pull/865

**Comment by mhagmajer** [comment]
@leebyron @wincent what do you guys think about this?

**Comment by mbrowne** [comment]
Now that the above PR is merged, I'm guessing this issue can be closed? I found this issue by Googling and it looked unresolved but I guess it's resolved.

**Comment by IvanGoncharov** [comment]
@mbrowne Yes your right it resolved in #382 
But not released yet so I will close this issue after release.

**Comment by IvanGoncharov** [comment]
Fixed
