### ISSUE TITLE
What exactly is "rootValue?"

### ISSUE THREAD

**Issue by KieronWiltshire** [graphql/express-graphql#338]
So I've tried to decipher exactly what `rootValue` does, and I've looked in the graphql docs to see if it's even referenced anywhere. I couldn't seem to find anything so I'm sure I'm missing something.

I would like to suggest that the `rootValue` explanation be linked or detailed a little more than what it already is to make it less confusing.

I would also appreciate it if someone could explain it to me here :)

**Comment by asiandrummer** [comment]
@KieronWiltshire - I think [this link to `graphql-js/src/execute.js`](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L121) should help! I'm updating the README to point to that file instead of `graphql-js`. Thanks for the suggestion!

**Comment by KieronWiltshire** [comment]
Thanks man!

**Comment by tarikhamilton** [comment]
If you're learning GraphQL and are still confused, just know you aren't alone. :P
