### ISSUE TITLE
Allow customize body size limit

### ISSUE THREAD

**Issue by luchillo17** [graphql/express-graphql#346]
Currently due to line [parseBody.js#L112](https://github.com/graphql/express-graphql/blob/master/src/parseBody.js#L112), the body of request limits to 100Kb.

I'm making an api that needs a bit more large body for some requests, for example 1Mb, can customization be added without the need to fork and modify directly?

**Comment by luchillo17** [comment]
Ping @wincent, what do you think about this feat? also my current fix (hack may be a better way to put it) is this:
* Tell my Webpack config to not use `express-graphql` as an external, but to bundle it to the `server.bundle.js` output file.
* Tell the Webpack config to parse [parseBody.js#L112](https://github.com/graphql/express-graphql/blob/master/src/parseBody.js#L112) and make string replacement on that limit variable like this:
```ts
export default {
  module: {
    rules: [
        {
          test: /parseBody\.js$/,
          use: [
            {
              loader: 'string-replace-loader',
              query: {
                search: 'var limit = 100 * 1024',
                replace: `var limit = '5mb'`,
                strict: true,
              },
            },
          ],
        },
    ]
  }
}
```

However the fact that i bundle that file generates certain error in my tests (and only in my tests, if i run the server it works ok):
```sh
FetchError{name: 'FetchError', message: 'request to http://localhost:50006/test failed, reason: socket hang up', type: 'system', errno: 'ECONNRESET', code: 'ECONNRESET'}
```

**Comment by wincent** [comment]
The hard-coded 100kb body limit does feel arbitrary. I'm not averse to making it configurable.

**Comment by luchillo17** [comment]
I'm already hitting the limit in my app in 2 different routes, using my workaround seems to break when used in tests and PM2, at this point i'll have to link it as submodule and edit such line.

**Comment by luchillo17** [comment]
Ok so i'm trying with SubModules and having issues with it in my tests as stated above, it's driving me crazy.

**Comment by luchillo17** [comment]
@wincent Man sorry about the ranting, i've tested a bit more and my issues have nothing to do with SubModules, most likely it has to do with latest changes from version `0.6.6` in registry, i've installed from the git repo and this issue happens:
![image](https://user-images.githubusercontent.com/9698639/28332106-1e24a15e-6bb9-11e7-93bd-0c02caa215e6.png)

**Comment by wincent** [comment]
Would need more info than is visible in that screenshot to know what's going on, and perhaps it should be a separate issue, to keep this issue for the feature request.

**Comment by luchillo17** [comment]
New issue: https://github.com/graphql/express-graphql/issues/351

**Comment by excitement-engineer** [comment]
I am also running into this issue. Would be great to specify the limit.

**Comment by luchillo17** [comment]
I've found that [apollographql/apollo-server](https://github.com/apollographql/apollo-server) doesn't parse the request itself, but let it to the standard `body-parser`, which would allow the dev to set the limit in a single place, i think that's a better approach.

Why does this repo implements that by itself? any custom features that `body-parser` doesn't allow?

**Comment by excitement-engineer** [comment]
@luchillo17 

You can enable a custom limit by using `body-parser`as middleware before `express-graphql`: 

```
app.use(bodyParser.json({limit: '1mb'}));
app.use(
  `/graphql`,
  graphqlHTTP(req => ({
    schema
  }))
);
```

**Comment by luchillo17** [comment]
@excitement-engineer Yes but that's just the `express` limit, `express-graphql` has it's own internal limit, that's what this issue is about.

**Comment by excitement-engineer** [comment]
If the contents of the body has already been parsed before entering express-graphql then express-graphql will not use the internal json parser contained in the library. See https://github.com/graphql/express-graphql/blob/master/src/parseBody.js#L112.

I am using this in my backend and I can confirm that the method I show above works.

**Comment by luchillo17** [comment]
Ok now i see it, if it's already parsed it will just return, if not it will try to parse according to the headers content type, i guess i should have looked at it, this is effectively the right way, closing now.

**Comment by gdrouet** [comment]
Using the same example as show by @excitement-engineer works but the error is not formatted by `GraphQL`. By default the error is wrapped in JSON property named `errors`

> {"errors":[{"message":"Invalid body: request entity too large."}]}

When fixing a custom limit the response format changes:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at readStream ...</pre>
</body>
</html>
```

How to keep the original error format?

**Comment by mfborman** [comment]
@gdrouet I'm having a similar issue. Did you find a solution to keep the original JSON formatting in the case your describe?

**Comment by mkonicek** [comment]
For me this simple solution worked:

```
// Add this before the GraphQL middleware
app.use(bodyParser({ limit: '1mb' }));
```

body-parser docs:
https://github.com/expressjs/body-parser/tree/1.16.0#limit

**Comment by MoSattler** [comment]
Trying to use bodyParser does not work for me. It causes this error:
> TypeError: Cyclic __proto__ value
