### ISSUE TITLE
[Bug] Latest git generates status 500 compared con V0.6.6

### ISSUE THREAD

**Issue by luchillo17** [graphql/express-graphql#351]
This is a weird one, i have an API with GraphQL, Karma for testing & PM2 for process cluster & load balancing.

If i install this repo from NPM registry, all green, however if i install it from the git repository, install with yarn the internal deps, and build, it works with node, but when inside the tests, and with PM2 it breaks with status code 500.

I'm debugging it to see where it breaks.

**Comment by luchillo17** [comment]
I've digged a bit more and this is my internal Error, since it was working before i installed your package, makes me think i have different `GraphQL` version installed: `"Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."`

**Comment by luchillo17** [comment]
Now i got an Stack Trace for you, here's a best error:
```ts
"Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
at invariant (/Users/aplicaciones2/Documents/tao-graphql-api/express-graphql/node_modules/graphql/jsutils/invariant.js:19:11)    
at validate (/Users/aplicaciones2/Documents/tao-graphql-api/express-graphql/node_modules/graphql/validation/validate.js:60:27)    
at /Users/aplicaciones2/Documents/tao-graphql-api/express-graphql/dist/index.js:140:52    
at process._tickCallback (internal/process/next_tick.js:109:7)"
```

Is it maybe because i'm using this repo from a submodule and graphql detects that they are called from different `node-modules` directories?

**Comment by luchillo17** [comment]
Ok maybe i'm doing it wrong, if i install from GitHub `yarn` don't support such thing, however this repo is made with Yarn so i cannot install it with NPM.

**Comment by luchillo17** [comment]
At last the workaround, had to install the one version in npm registry, copy the file of limit, edit and save, then put an `npm` `postInstall` script, that paste such file ni the path inside node_modules, and hack complete (still hope you allow for customization there).

**Comment by IvanGoncharov** [comment]
@luchillo17 Sorry for the late response. You should always have only one instance of `graphql` library in your `node_modules`. You can check it using `npm ls graphql` and you should see the single version.

It's not a problem with `express-graphql` since it support all latest `graphql` versions as peer dependency.
