### ISSUE TITLE
post-execution middleware is failing to be called

### ISSUE THREAD

**Issue by chemdrew** [graphql/express-graphql#374]
Inside the request handler the next callback is not being called on completion

This does not allow for using the after event in restify `res.on('after', () ={})` or doing middleware chaining in express

```
app.use(<pre-execution middleware>);

app.use('/graphql', graphqlHTTP({
  schema: schema,
}));

app.use(<post-execution middleware>);
```

Could we get this added in by default or add a toggle in the options to forward the middleware?
I'll create the PR if this is deemed valid.
Thanks!

**Comment by chemdrew** [comment]
easy fix on server implementation - closing issue

```
const graphqlHandler = (req, res, next) => {
  const graphqlHTTPHandler = graphqlHTTP({
    schema: schema,
    graphiql: true
  });
  graphqlHTTPHandler(req, res).then(() => {
    next();
  }).catch((e) => {
    next(e);
  });
};

server.get('/graphql', graphqlHandler);
server.post('/graphql', graphqlHandler);
```

**Comment by vivex** [comment]
It works fine but i am not able to set anything to response using post middle-wares as response is already sent by graphql
