### ISSUE TITLE
Missing API to configure GraphiQL

### ISSUE THREAD

**Issue by lightsprint09** [graphql/express-graphql#376]
We want to provider a defaultQuery to GraphiQL, but it seems there no way to to that.

**Comment by wincent** [comment]
Thanks for the question, @lightsprint09.

I believe you should be able to do this, or at least, that was my opinion back in February!

https://github.com/graphql/express-graphql/issues/211#issuecomment-279120907

I'm going to close this for now, but if you don't have any luck and have further questions or thoughts just comment and we can continue the discussion.

**Comment by lightsprint09** [comment]
Wouldn't  it be better to expose a configuration parameter called `graphiqlConfiguration` which takes the [official GraphiQL config](https://github.com/graphql/graphiql#usage) every knows.

**Comment by kaelig** [comment]
I agree, it'd be really useful to be able to directly override graphiql's props.
