### ISSUE TITLE
GraphiQL 404

### ISSUE THREAD

**Issue by GuillaumeUnice** [graphql/express-graphql#378]
Hi every,

I use express-graphql with graphiql true. 
I made a programmatically implementation which works but I would like with the buildSchema function.
And when I run the app I have no console error and just just a 404 on GraphiQL "cannot GET /" that all.
So I think it was my code and I decide to just copy past the official doc and past the following code:
http://graphql.org/graphql-js/running-an-express-graphql-server/
...and I have the same problem maybe it's a problem with the last version:

```
"express-graphql": "^0.6.7",
"graphql": "^0.10.5",
```

Any idea? Someone have ever met this kind of issue?
Thanks for all

**Comment by mouhsinelonly** [comment]
facing the same issue does anyone have a clue ?!

**Comment by GuillaumeUnice** [comment]
Ahah I'm always blocked by that but now I'm not only XD
If you want you can directly use Apollo Library which wrap buildSchema but I don't have any kind of explanation about this issue :s

**Comment by jamrizzi** [comment]
I'm having the same issue

**Comment by IvanGoncharov** [comment]
> So I think it was my code and I decide to just copy past the official doc and past the following code:
http://graphql.org/graphql-js/running-an-express-graphql-server
...and I have the same problem

@GuillaumeUnice @mouhsinelonly @codejamninja Sorry for the late response.
If you using official sample than you should open `http://localhost:4000/graphql`

>  404 on GraphiQL "cannot GET /" 

It looks like you are calling `http://localhost:4000/` instead.

Feel free to reopen if it doesn't solve your issue.
