### ISSUE TITLE
Error-highlighting and tool tips do not work

### ISSUE THREAD

**Issue by ErikWittern** [graphql/express-graphql#396]
Currently, error highlighting and tool tips do not work in the GraphiQL instance served by this library. The error seems related to known GraphiQL issues (cf. https://github.com/graphql/graphiql/issues/534 and https://github.com/graphql/graphiql/issues/611). Updating the GraphiQL version to the latest (`0.11.5`) should fix this problem.

**Comment by fpoumian** [comment]
I'm also not getting any error highlighting with the following setup:

```
"express": "^4.16.2",
"express-graphql": "^0.6.11",
"graphql": "^0.11.7",
```
