### ISSUE TITLE
How to return a query type or calling root query when needed?

### ISSUE THREAD

**Issue by shtse8** [graphql/express-graphql#399]
```
type Book {
  id: ID!
  name: String!
}

type User {
  id: ID!
  name: String!
  books: [Book]!
}

type Query {
  books(
    userId: Int
    offset: Int
    limit: Int
  ): [Book]!
  user(
    id: Int!
  ): User
}
```
```
let resolvers = {
  Query: {
    books: (_, {userId, offset, limit}) => {
      return Book.find({
        userId: userid,
        offset: offset,
        limit: limit
      })
    },
    user: (_, {id}) => {
      return User.find({
        id: id
      })
      // return {
      //  id: 1,
      //  name: 'John Chan'
      // }
    }
  },
  User: {
    books: (user) => {
      // For reusing offset, limit of books, I want to calling query.books here, how can I do it?
    }
  }
```

ATM, I need to do the offset, limit and filters every time for returning `books`. I want to simplify it, any helps? thanks.

**Comment by ceracera** [comment]
If you are trying to do what I think you are :) you can access parent type from child (User from Books) from the `obj` argument on the resolve function. See the GraphQL docs: [http://graphql.org/learn/execution/#root-fields-resolvers](url)

**Comment by IvanGoncharov** [comment]
@shtse8 Sorry for the late response.
> I need to do the offset, limit and filters every time for returning books. I want to simplify it, any helps? thanks.

This package is handled HTTP transport for GraphQL servers so questions on how to define your schema are beyond its scope. I would recommend taking a look at this package: https://github.com/graphql/graphql-relay-js
I also recommend you to ask this question on StackOverflow.
