### ISSUE TITLE
Better error stack in response

### ISSUE THREAD

**Issue by tomatau** [graphql/express-graphql#4]
Would be nice if the error stack in responses could contain more detailed information.

I incorrectly imported some functions for my schema and `undefined is not a function` without any line numbers was very painful to track down the source of the problem.

```
Warning: Server request for query `AppHomeRoute` failed for the following reasons:

1. undefined is not a function
   query AppHomeRoute{game{id,..._0c28183ce}} fragment _1452748
                      ^^^
```

I'm sure that more experience using express-graphql would make this error's location far easier to find based on the flagging of `game{`. I had difficulty finding the actual function that was undefined as I only knew to look somewhere within the game query type.

**Comment by leebyron** [comment]
Merging this into https://github.com/graphql/graphql-js/issues/28 where it's being discussed.

I agree that better error reporting is a priority.
