### ISSUE TITLE
Unmet Peer dependency

### ISSUE THREAD

**Issue by dmytro-kerest** [graphql/express-graphql#405]
Latest express-graphql does not support latest graphql 

`    {
    "express-graphql": "^0.6.11",
    "graphql": "^0.12.3"
}
`

**Comment by thiagovilla** [comment]
Same issue here

**Comment by oqx** [comment]
Hey folks,

Check what version of npm you're running:
`npm -v`

Update to the latest (this will remove your current version).

Mac:
`sudo npm install -g npm`

Other:
`npm install -g npm`

More info here:
https://stackoverflow.com/questions/6237295/how-can-i-update-node-js-and-npm-to-the-next-versions

That did the trick for me -- hopefully it works for you, too.

**Comment by IvanGoncharov** [comment]
@dmytro-kerest @thiagovilla 📦 v0.6.12 released with support for graphql v0.12.x and v0.13.x.
