### ISSUE TITLE
User session undefined

### ISSUE THREAD

**Issue by SLedunois** [graphql/express-graphql#413]
Hello,

I try to create a GraphQL application using Apollo, Express GraphQL and Passport. Here is a piece of my server file :
```js
app.use(session({
  secret: configuration.session.secret,
  resave: false,
  saveUninitialized: false,
}));

const passport = require('./configuration/authentication');

app.use(passport.initialize());
app.use(flash());
app.use(passport.session());

const index = require('./routes/index');
const auth = require('./routes/auth');

app.use('/', index);
app.use('/auth', auth);
app.use('/graphql', bodyParser.json(), (req, res, next) => {
  console.log(req.session);
  return graphqlExpress({
    schema,
    context: { user: req.session.passport.user },
    tracing: true,
    cacheControl: true,
  })(req, res, next);
});

if (NODE_ENV === 'dev') {
  app.use('/graphiql', graphiqlExpress({
    endpointURL: '/graphql',
  }));
}
```

The problem : After getting authenticated, a `POST` on `/graphql` returns that log :
```
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }
````

The session doesn't return any user. When I send the same query using GraphiQL, the log returns a user in the session :
```
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: { user: '5a69e28d5d3b7f09a7e4bc7f' } }
```

Currently, I don't find my mistake in the code. Can you help me ?

Thank you,

SLedunois

**Comment by SLedunois** [comment]
I found the mistake. The issue is not in express-graphql. I'm using GraphQL and Apollo client. After investigate, I found that the cookie was not sent from the client. I resolved the issue by adding `credentials: 'same-origin'`to the Applo Http Link

```js
const link = new HttpLink({
  uri: '/graphql',
  credentials: 'same-origin',
});
```

I close the issue.

**Comment by cadenzah** [comment]
`credentials` option should be set to `'include'`, not `'same-origin'`.
