### ISSUE TITLE
What is the expected status code on variable validation errors? 

### ISSUE THREAD

**Issue by zya** [graphql/express-graphql#417]
Lets say we have a schema like below:

```
enum Platform {
  web
  tv
  mobile
}

type Query {
  myQuery(platform: Platform!): MyResponse
}
```

And this is my query:
```
get($platform: Platform!) {
     myQuery(platform: $platform) {}
 }
```
And I make a POST request like below:
```
POST /myendpoint

{
   "query": "the above query stringified",
   "variables": {
       "platform": "watch"
    }
}
```
In this case, I am using an invalid variable that fails the request.
When making the above request, we are getting 200 status code with a response containing validation errors. Because `watch` is not a member of the `Platform` enum.

However, if I make the request without using variables, I'll get 400.
```
myQuery(platform: watch) {}
```

Wanted to check if this is expected behaviour before moving on to finding implementation details and potentially attempting to raise a PR with a fix.

**Comment by IvanGoncharov** [comment]
@zya It's normal that in-place invalid error return 400 since it's validation that can be done beforehand (e.g. [eslint-plugin-graphql](https://www.npmjs.com/package/eslint-plugin-graphql)).
On the other hand validation of query, variables happen during execution so it should result in `500`.  

However, the current implementation has a bug:
https://github.com/graphql/express-graphql/blob/6fc7baf8b161f4e6ba34c00dbff76a46a72cbca7/src/index.js#L292-L299

It missing case where `result.data === undefined` 🐞

**Comment by zya** [comment]
> On the other hand validation of query variables happen during execution so it should result in 500

Are you sure about this? Intuitively, I would expect to get a 400 in this case. Although by looking at the code, there is no way of achieving that other than parsing the error messages after the execution and figuring out whether there was a validation error or any other.

**Comment by IvanGoncharov** [comment]
Values inside query validated during `Validation` phase:
http://facebook.github.io/graphql/October2016/#sec-Compatible-Values

Values in query variables validated during `Execution` phase:
http://facebook.github.io/graphql/October2016/#sec-Coercing-Field-Arguments

**Comment by zya** [comment]
Yes, but the spec does not have any opinions on status code.
Intuitively, any validation error should result in 400 status in my opinion. Is that not right?

**Comment by IvanGoncharov** [comment]
@zya 
> Intuitively, any validation error should result in 400 status in my opinion.

I would argue that any error during execution of request shoul result in 5xx.

But I agree, that mapping of GraphQL semantics on HTTP status codes is terra incognita.
Anyway, I think we both agree that it shouldn't be 200. Right?

**Comment by zya** [comment]
> But I agree, that mapping of GraphQL semantics on HTTP status codes is terra incognita.
Anyway, I think we both agree that it shouldn't be 200. Right?

Yes, we definitely agree on that. 200 does not make any sense in this case.

**Comment by JontyUsborne** [comment]
When patching this issue I've noticed that [making a GET request with missing operation name](https://github.com/graphql/express-graphql/blob/master/src/__tests__/http-test.js#L252) responds similarly...
```
{
  data: undefined,
  errors: [{
    message: 'Must provide operation name if query contains multiple operations.'
  }]
}
```
...but also returns a 200 status code. 

I know that's technically a different issue, but do we agree that too should not be returning 200?

**Comment by zya** [comment]
I think we can interpret having a result with no `data` as a fatal execution error and result in 500. And if I'm not mistaken, doing that will solve both of the issues mentioned here by returning 500 in both cases.

**Comment by IvanGoncharov** [comment]
> I think we can interpret having a result with no data as a fatal execution error and result in 500.

Fully agree. Plus it's very easy to implement 👍 

> But a contributor such as @IvanGoncharov could help answer that question better

Contributor label means I made a few commits to this repo but I don't have commit rights :(

P.S. Previous maintainer of this projects switched to another Facebook team so this repo is inactive. 
I will try to contact him to find out how we can merge simple fixes such as this one + finally update `graphql` peer dependency to  `0.13.x`.

**Comment by JontyUsborne** [comment]
Yup, agreed. Intuitively I would expect 400 in both cases, given they are invalid requests, but agree 500 makes sense from an express perspective as the validation occurs within the graphql execution.

Thanks for the help @IvanGoncharov, we'll open a PR and see if anyone's around to pick it up.
