### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by rblakeley** [graphql/express-graphql#42]
Would https support be possible with this repo or would that be set up with Express before the main constructor from this project gets passed to `express.use`?

**Comment by rturk** [comment]
You can always implement HTTPs via a proxy server. In my use I use nginx as a SSL offload engine

**Comment by leebyron** [comment]
You absolutely can do this. This library only provides a middleware for Express, and that middleware can be used along with any configuration for Express, including one that supports HTTPS. If you do some googling you will find examples of using Express in HTTPS, https://gist.github.com/ryanhanwu/5321302 came up as an interesting example.

I don't think any changes are necessary to this middleware to work in an HTTPS Express, but please open a new issue if you encounter anything concrete that must change.
