### ISSUE TITLE
middleware after graphql response

### ISSUE THREAD

**Issue by crbonilha** [graphql/express-graphql#420]
I perform an operation after my controller have sent their response, by calling the "next" callback.
The problem is the express-graphql doesn't receive nor call the "next" callback.

Is there a workaround this?
My suggestion is to have it receive the "next" parameter, and then if the user set a "callNext" option as true the "next" callback is called after the response is sent.

**Comment by vivex** [comment]
https://github.com/graphql/express-graphql/issues/279
