### ISSUE TITLE
`formatError` error ignores custom error properties

### ISSUE THREAD

**Issue by teckays** [graphql/express-graphql#421]
I am throwing a custom error inside the resolver with additional parameters, unfortunately all custom fields are being stripped out from the `formatError: error => {}` callback.

```
// error 
class CustomError {
    constructor () {
        this.foo = 'bar'
    }
}

// resolver
try {
     throw new CustomError()
}

// graphQL
...
formatError: err => {
    console.log(err.foo) // undefined
}
```

**Comment by teckays** [comment]
Sorry, figured out that this is actually a bug in the `graphql-js` package

**Comment by teckays** [comment]
A "not very obvious `err.originalError` solution" found here: https://github.com/graphql/graphql-js/issues/1192

**Comment by IvanGoncharov** [comment]
@teckays You don't need to replace `formatError` at all. If you do:
```js
class CustomError {
    constructor () {
        this.extensions = { foo: 'bar' };
    }
}
```
It will be automatically exposed 🎉

**Comment by kendallroth** [comment]
> @teckays You don't need to replace `formatError` at all. If you do:
> 
> ```js
> class CustomError {
>     constructor () {
>         this.extensions = { foo: 'bar' };
>     }
> }
> ```
> 
> It will be automatically exposed 🎉

This is unfortunately incorrect, as `extensions` will not be exposed in the thrown error.

**Comment by vnphanquang** [comment]
> @teckays You don't need to replace `formatError` at all. If you do:
> 
> ```js
> class CustomError {
>     constructor () {
>         this.extensions = { foo: 'bar' };
>     }
> }
> ```
> 
> It will be automatically exposed 🎉

I think this piece of information would be very helpful if added to the documentation (README). [formatError](https://github.com/graphql/graphql-js/blob/master/src/error/formatError.js) is also helpful.
