### ISSUE TITLE
extensions field

### ISSUE THREAD

**Issue by t0lkman** [graphql/express-graphql#423]
Is there any way to change the name of the extensions field? I want to call it "userInfo"
or in graphql world return extensions together with data fields is the way to do?

**Comment by IvanGoncharov** [comment]
@t0lkman Response can't contain anything except `data`, `errors`, `extensions`:
> To ensure future changes to the protocol do not break existing servers and clients, the top level response map must not contain any entries other than the three described above.

http://facebook.github.io/graphql/October2016/#sec-Response-Format

**Comment by IvanGoncharov** [comment]
@t0lkman Can I close this issue?

**Comment by t0lkman** [comment]
I'll close, tnx!
