### ISSUE TITLE
I try disable CORS

### ISSUE THREAD

**Issue by korolariya** [graphql/express-graphql#431]
```
app.use(
    '/graphql', (req, res) => {
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Headers', 'origin, content-type, accept');
        graphqlHTTP({
            schema  : compiledSchema,
            graphiql: true,
        })(req, res);
    },
);
```
but I can't turn off

**Comment by IvanGoncharov** [comment]
@korolariya You need to add `cors` package and add `app.use(cors());` before you defined graphql endpoint.

**Comment by IvanGoncharov** [comment]
Here is an example:
https://github.com/graphql/swapi-graphql/blob/master/src/server/main.js#L18

**Comment by korolariya** [comment]
thanks, import like this
`import * as cors from "cors";`
 is working

**Comment by umutyerebakmaz** [comment]
yarn add cors 
import * as cors from "cors";
app.use('/graphql', cors(), graphqlHTTP((req, res, params) => ({ schema, context: { req, res, params } })));
