### ISSUE TITLE
No simple way to wrap execution

### ISSUE THREAD

**Issue by jamiehodge** [graphql/express-graphql#432]
It appears as though the only way to wrap the execution promise for tracing/instrumentation is by misusing the extensions function. It would be very nice if one was able to define a wrapper function (that returned the same type), for tracing purposes.

i.e.

```
tracer: ({ query, variables, execution: Promise<...> }) => trace(query, execution...)

```

**Comment by IvanGoncharov** [comment]
@jamiehodge I'm currently working on #391 and plan to include it into next release.
Is it something similar to what you have in mind?

**Comment by jamiehodge** [comment]
@IvanGoncharov this looks very helpful. Thank you.
