### ISSUE TITLE
change BSD+Patents License to MIT license

### ISSUE THREAD

**Issue by junminstorage** [graphql/express-graphql#434]
One of the issues when I tried to adopt express-graphql is the license. 
React was also under BSD, but its license is changed to MIT license to allow wider adoption. See link below:
https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b

**Comment by osecki** [comment]
:+1:

**Comment by treycordova** [comment]
Took @leebyron's relicensing work from [graphql-js](https://github.com/graphql/graphql-js) and simply applied it here in https://github.com/graphql/express-graphql/pull/442. I'll leave it to FB to decide the rest.

**Comment by frankrafael** [comment]
+ 1 on this one! I really love this lib but this is the only thing preventing me from using it...

**Comment by IvanGoncharov** [comment]
Fixed in #515
