### ISSUE TITLE
aggregate function not mapping to type, returns null

### ISSUE THREAD

**Issue by Bradly-kunthrope** [graphql/express-graphql#438]
I am testing a basic aggregation function using counts from Sequelize and here's my type **Counts**:
![image](https://user-images.githubusercontent.com/29423573/40134166-373a50ae-5974-11e8-8300-2f476fe7b31e.png)

I am using countBookings as my query for aggregate functions and here's my resolver for the query:
![image](https://user-images.githubusercontent.com/29423573/40134266-7889803e-5974-11e8-8de5-b15c5c21a5c1.png)

The query that it outputs is this:
![image](https://user-images.githubusercontent.com/29423573/40134292-8aa2e8dc-5974-11e8-97b6-933c2565e0f6.png)

So I tested it out in my psql shell and it's working fine:
![image](https://user-images.githubusercontent.com/29423573/40134317-9e683976-5974-11e8-88f6-e7ee3ca6c2ff.png)

But it returns null in my graphql playground except for the one that is grouped by (section, in this case):
![image](https://user-images.githubusercontent.com/29423573/40134931-6e01294e-5976-11e8-9ce0-45163a0a3c8f.png)

Is there something I missed out? Or is this a bug? This is the answer I tried following to with this example: [https://stackoverflow.com/a/45586121/9760036](url)

**Comment by IvanGoncharov** [comment]
Closing since it was answered on SO
