### ISSUE TITLE
Uploading file using graphql

### ISSUE THREAD

**Issue by macin40** [graphql/express-graphql#440]
How can i upload file using angular 5 + Apollo client using apollo express and Node

**Comment by ChampTiravat** [comment]
Yes you can. using this lib https://github.com/jaydenseric/apollo-upload-client

**Comment by eedfa** [comment]
I can`t find reliable example with apolllo-upload-client and express-graphql

**Comment by jaydenseric** [comment]
> using apollo express

This is the repo for `express-graphql`, a different GraphQL server to Apollo Server Express.

Regardless, you will be interested in checkout [`graphql-upload`](https://github.com/jaydenseric/graphql-upload) - It supports both of these GraphQL servers and more.

@ChampTiravat is right, if you are using Apollo Client you can use [`apollo-upload-client`](https://github.com/jaydenseric/apollo-upload-client).

**Comment by danielrearden** [comment]
Example from the `graphql-upload` docs:

```
const express = require('express');
const graphqlHTTP = require('express-graphql');
const { graphqlUploadExpress } = require('graphql-upload');
const schema = require('./schema');

express()
  .use(
    '/graphql',
    graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }),
    graphqlHTTP({ schema })
  )
  .listen(3000);
```
