### ISSUE TITLE
extensions - context is gone ?

### ISSUE THREAD

**Issue by ml-milkmidi** [graphql/express-graphql#446]
bug version 0.6.12
github source code is correct.
but npm version
(express-graphql/dist/index.js) line 175
```
      return Promise.resolve(extensionsFn({
          document: documentAST,
          variables: variables,
          operationName: operationName,
          result: result
          // context: context    should add this code
```
Thanks.

**Comment by IvanGoncharov** [comment]
@ml-milkmidi It's not released yet 😞 We are working on the first stable release of `graphql-js` and this project is next on my list afterwards
