### ISSUE TITLE
Documentation is Out of Sync with Code (no context for extentions)

### ISSUE THREAD

**Issue by dhurlburtusa** [graphql/express-graphql#450]
PR #441 was merged and has updated the README.md here on Github. However, a release was not made after the merge.

**Comment by nigelterry** [comment]
And I just spent a couple of hours thinking I was going insane until I found this issue.

**Comment by mehdibeldji** [comment]
Is it possible to create a release please ?

**Comment by dhurlburtusa** [comment]
It would be nice to prevent this in the future too. I'd recommend branching `master` to a `develop` branch (you can follow the [Gitflow](https://nvie.com/posts/a-successful-git-branching-model/) branching model). Then changes to files such as the README that everyone uses for guidance is not out of sync with the latest release (at least if they are looking as the README on the master branch which is the default branch for this repo).

**Comment by AGS-** [comment]
Closing since this is now resolved.
