### ISSUE TITLE
How To Escape Parameters When Using Custom Objects

### ISSUE THREAD

**Issue by pepie** [graphql/express-graphql#453]
Hello.

Given a custom mutation object defined as listed below, what is the best way to escape parameters, to avoid having to manual replace double quotes and perform other cleanup for the query?

**THE CLIENT SIDE**

```js
let params = {
  title: 'event title',
  description: 'event details here...',
};
```

Query:

```js
{
  query: `{mutation{updateEvent(event_id:\"${id}\", input: ${params} ){event_id, event_description}}`;
}
```

**Result:**
`Syntax Error: Expected Name, found <EOF>`

**Obrservations**

- JSON.stringify(params) is not enough, as it will produce input: {key: **"**value**"**}
  The proper format would need to be input: {key: **\"**value**\"**, ...}
- I can further clean the string, by escaping double quotes, but it seems like their should be a better way.

**SERVER SIDE**
Here's the graph mutation and object definitions:

```js
const EventInput = new GraphQLInputObjectType({
    name: 'EventInput',
    fields: () => ({
        event_type_id: {type: GraphQLInt},
        event_title: {type: GraphQLString},
        event_description: {type: GraphQLString},
        <truncated>
    })
});

const Mutations = new GraphQLObjectType({
        name: 'Mutation',
        fields: ()=>({
            updateEvent:{
                type: Event,
                args: {
                    event_id: {type: GraphQLString},
                    input: {type: EventInput}
                },
                resolve(_, args, context){
                    const event_id = args.event_id;
                    const user_id = context.user.user_id;
                    <truncated>
                    return service.findEventById(event_id);
                }
            }
        })
});
```

**Comment by IvanGoncharov** [comment]
@pepie Please use query variables: https://graphql.org/learn/queries/#variables
