### ISSUE TITLE
GraphQL and HTTP2

### ISSUE THREAD

**Issue by AchuthSankar** [graphql/express-graphql#454]
This is a new feature requirement:
Could we use GraphQL via HTTP2 ?

**Comment by joelgetaction** [comment]
Any updates on this?

**Comment by ArmanNisch** [comment]
Think this is a very valid discussion to have... does GraphQL makes sense with HTTP2?

**Comment by Fr33maan** [comment]
Graphql as a query language looks really good because in 1 fetch, you can get deep associations. The only issue now is that the longest query to resolve will be the time to resolve the initial fetch. With http2 we could have several server pushes for populating the result little by little.

**Comment by pranaypratyush** [comment]
@Fr33maan https://github.com/dunglas/vulcain seems to be doing the same but I think it would need client-side changes as well. 
Using HTTP/2 as the transport without changes to graphql should already show some improvements in performance.

**Comment by danielrearden** [comment]
`express-graphql` is just middleware for Express, so there's no reason you can't use it with HTTP2. You can use `spdy` to create an HTTP2/SPDY server that'll work with your Express instance:

```
const spdy = require('spdy')
const app = require('express')()

// apply your middleware here

spdy
  .createServer({ key, cert }, app)
  .listen(port)
```
