### ISSUE TITLE
Refresh schema on runtime

### ISSUE THREAD

**Issue by naivefun** [graphql/express-graphql#455]
We give users the ability to define data model and generate GQL schema on the run, so how do I refresh the schema when there is new model added?

**Comment by naivefun** [comment]
After some research I find out that the schema seems just a reference to `options.schema`, maybe I can simply update options to archive what I need. TBT.

**Comment by IvanGoncharov** [comment]
@naivefun Instead of `options` you can pass callback that return options:
```js
app.use('/graphql', graphqlHTTP(async (request, response, graphQLParams) => ({
  schema: MyGraphQLSchema,
  rootValue: await someFunctionToGetRootValue(request),
  graphiql: true
})));
```

**Comment by BkunS** [comment]
I have the same question, but a little different in details:
For example: 
If I store types in DB, sth like: ```Types: [{ name: "test", type: "string"}, { name: "score", type: "float" }]```
Whenever server starts or APIs that change Types data in DB are called:
```
let fields = { name: "default", type: GraphQLString };
updateTypes() {
  fields = await getTypesFromDB() // then convert fields to { ${name}: { type: GraphQL${type}, ... }
  const TestType = new GraphQLObjectType({
    name: 'TestType',
    fields: () => ({ ...fields })
  })
  module.exports = TestType
} 
```
The exported value gets updated, but in app.js:
```
import schema from './schema'
app.use('/graphql', graphqlHTTP({
  schema: schema
  ...
))
```
It's still using the old schema. Is there anyway to make schema use the updated value?

**Comment by yuanxuzhang** [comment]
> I have the same question, but a little different in details:
> For example:
> If I store types in DB, sth like:
> 
> ```
> Types: [
>   { name: "test", type: "string" }, 
>   { name: "score", type: "float" }
> ]
> ```
> 
> Whenever server starts or someone called APIs that change Types data in DB, it triggers updateTypes():
> 
> ```
> let fields = { name: "default", type: GraphQLString };
> updateTypes() {
>   fields = await getTypesFromDB() // then convert fields to { ${name}: { type: GraphQL${type}, ... }
>   const TestType = new GraphQLObjectType({
>     name: 'TestType',
>     fields: () => ({ ...fields })
>   })
>   module.exports = TestType
> } 
> ```
> 
> The exported value gets updated, but in app.js:
> 
> ```
> import schema from './schema'
> app.use('/graphql', graphqlHTTP({
>   schema: schema
>   ...
> ))
> ```
> 
> It's still using the old schema. Is there anyway to make schema use the updated value?

Hi: BknuS
Did you find anyway to make schema use the updated value?  thanks.

**Comment by truptivishe-gep** [comment]
Hi , did anyone find a solution for this?

**Comment by johanlelan** [comment]
Hi, I am looking for the same @yuanxuzhang ;). Our types are stored into DB and when an update event raise we want to update the GraphQL Schema on-the-fly.

How to refresh by code the computed `graphqlHTTP` schema @IvanGoncharov ?

**Comment by KEMBL** [comment]
@johanlelan it is possible to do with types the same as @IvanGoncharov made for resolvers, i.e.:

    schema: await someFunctionToGetTypesValue(request),
    rootValue: await someFunctionToGetRootValue(request)
