### ISSUE TITLE
validateSchema is called on every request

### ISSUE THREAD

**Issue by polco** [graphql/express-graphql#456]
The schema validation could be cached (to allow updating the schema at runtime) or just done once when the middleware is created, or am I missing something ? :)

**Comment by IvanGoncharov** [comment]
@polco Thanks for the suggestion. It's already done inside `validateSchema` see here:
https://github.com/graphql/graphql-js/blob/6f70c862e38e227de4ad474806eb606e742f5fb5/src/type/validate.js#L65-L68
