### ISSUE TITLE
Unable to install graphql-import and unable to find peer of graphql@^0.11.0 || ^0.12.0 || ^ 0.13.0 || ^14.0.0

### ISSUE THREAD

**Issue by Rudra815** [graphql/express-graphql#462]
Facing issue when doing, npm i -g graphql-import@0.7.1 :
Error : npm WARN graphql-import@0.7.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^
0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.

Where do I find the peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0
Please some one help me

**Comment by IvanGoncharov** [comment]
@Rudra815 Please report it to `graphql-import` repo.

**Comment by Rudra815** [comment]
@IvanGoncharov unable to find graphql-import repo.. can you put the link for this repo

**Comment by IvanGoncharov** [comment]
@Rudra815 https://github.com/prisma/graphql-import
