### ISSUE TITLE
Anyway to rate limit a specific graphql call?

### ISSUE THREAD

**Issue by arik-gamerlink** [graphql/express-graphql#465]
Hey great module,

I was wondering if anyone was able to figure out a way to rate limit a specific graphQL call. 

Right now I'm using express-rate-limit to rate limit the entire /graphQL endpoint however small graphQL calls need to be limited more than others. 

Has anyone been able to accomplish this?

**Comment by danielrearden** [comment]
There's several libraries available that provide this functionality. You might want to check out [graphql-rate-limit](https://github.com/teamplanes/graphql-rate-limit) which looks like it works both standalone and alongside with GraphQL Middleware.
