### ISSUE TITLE
Need the feature of getting all of the values from the collection or table without giving all of the specific fields every time?

### ISSUE THREAD

**Issue by svenkatesh-nyros** [graphql/express-graphql#466]
Can you please provide the feature of getting all of the response values from the query type without giving each and every params every time. As it is time taking and required most of the time in api calls.

example:

```graphql
query {
  getService(id:"55666") { * }
}
```

And another feature is
-> add option of giving query param to not get the specific field and get the remaining fields of the query. like in MongoDB {id: 1, name: 1, \_\_v: -1 }

example :

```graphql
query {
  getUser(id: "554645"){
    password: -1
  }
}
```

for getting the every fields of the user data by leaving the password value.

**Comment by IvanGoncharov** [comment]
@svenkatesh-nyros This is a repo for the reference implementation of GraphQL server and not GraphQL specification. Your proposal is discussed and answered here:
https://github.com/facebook/graphql/issues/127#issuecomment-163658834
