### ISSUE TITLE
Flow type error for imported $Request type from express

### ISSUE THREAD

**Issue by mgrip** [graphql/express-graphql#468]
Some types are imported from express [here](https://github.com/graphql/express-graphql/blob/master/src/parseBody.js#L18), but express is a devDependency so the module is missing when `express-graphql` is used in other projects.

Im getting the flow error `Cannot resolve module express` in my own project

**Comment by IvanGoncharov** [comment]
@mgrip Sorry for the delay.
Fixed in #527 and will be released shortly.
