### ISSUE TITLE
How to generate documentation?

### ISSUE THREAD

**Issue by marcospgp** [graphql/express-graphql#469]
Sorry to be opening an issue, I couldn't tell a better place to ask this:

How does one go about generating documentation for a GraphQL API? Is GraphiQL sufficient?

How could I describe an endpoint and then generate documentation that includes that description?

When using REST, I usually set up a system with jsdoc style Swagger comments with each endpoint handler in the code. Not sure how to do something like this with GraphQL in Express.

Thanks!!

**Comment by IvanGoncharov** [comment]
@marcospgp Sorry for the delay.
Documentation generation is handled by separate tools, here is a good introduction to this topic https://www.youtube.com/watch?v=aJk99MSVj0Y
