### ISSUE TITLE
Schema-based permission layer

### ISSUE THREAD

**Issue by mchogithub** [graphql/express-graphql#475]
How can I add a **schema-based permission layer** (fields and args value permission level)?
I have tried to use the **validationRules** option with additional validation rules, however it is not asynchronous.
I would like to avoid using third-party solutions like apollo, graphql-yoga etc ..

**Comment by IvanGoncharov** [comment]
@mchogithub Sorry for the delay.
Our position is that Authorization should be handled bellow GraphQL layer:
https://graphql.org/learn/authorization/
But you can use 3rd-party solutions that work with `express-graphql`, e.g.:
https://github.com/maticzav/graphql-shield#others-using-graphql-middleware
