### ISSUE TITLE
Can it logout error's stack to help users finding out where the error came out ?

### ISSUE THREAD

**Issue by Pingze-github** [graphql/express-graphql#476]
For example, I write a `JSON.parse('{{')` in resolver functions. That will cause a Error when querying.

I query in GraphiQL, got:

```
{
  "errors": [
    {
      "message": "Unexpected token { in JSON at position 1",
      "locations": [
        {
          "line": 31,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ],
  "data": {
    "post": null
  }
}
```
Only the Error.message is returned, and the Error.stack is missing. I cannot locate where the error comes from.

I wish to see full error stack in my backend terminal, like:

```
SyntaxError: Unexpected token { in JSON at position 1
    at JSON.parse (<anonymous>)
    at main (G:\graphQLTest\demo\demo.js:111:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Is there a possible way to do this?

**Comment by IvanGoncharov** [comment]
@Pingze-github Please see this section:
https://github.com/graphql/express-graphql#debugging-tips
