### ISSUE TITLE
customFormatErrorFn typescript error TS7006: Parameter 'error' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by francoisromain** [graphql/express-graphql#481]
Hello

when I replace the deprecated `formatError` by `customFormatErrorFn` in a typescript project, there is an error when compiling: 

```
error TS7006: Parameter 'error' implicitly has an 'any' type.
```

**Comment by IvanGoncharov** [comment]
@francoisromain Thanks for reporting 👍 
TS definitions tracked in the `DefinetlyTyped` repo, and I submitted PR there:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34914
