### ISSUE TITLE
Support custom document loading

### ISSUE THREAD

**Issue by williambailey** [graphql/express-graphql#483]
It would be nice to be able to provide a function to support custom document loading. Being able to extend/augment/replace the `new Source(...)`, `parse(source)`, `validateFn(...)` process would make implementing functionality like persisted document storage easier and also allow the server to skip the document parsing and validation stages for known/frequent documents.

**Comment by IvanGoncharov** [comment]
@williambailey Great suggestion 👍 
I think the ability to replace `parse` is a great feature.
If you want to work on PR it should be very similar to #391

> extend/augment/replace the new Source(...),

`Source` is a very primitive class so I don't think we should bother to replace it.
You can always access the original query as `source.body`.
https://github.com/graphql/graphql-js/blob/cd80f94edc584c5cf3258d27b6f91ab3b72f0cce/src/language/source.js#L31-L44

**Comment by IvanGoncharov** [comment]
I'm closing this issue since progress is tracked in #484
