### ISSUE TITLE
How to set custom headers on the response ?

### ISSUE THREAD

**Issue by Aaike** [graphql/express-graphql#5]
how can i add custom headers to the response, for example to enable cors ?

**Comment by leebyron** [comment]
You should be able to do this by installing an express middleware that handles CORS before the graphql middleware

**Comment by Aaike** [comment]
ah yes , but that would enable it for all the routes right ? i was looking to just allow this graphql route.

what i did for now was to change the plugin code a little bit so it also passes the response into the callback , like so : 
```
app.post('/', graphQLHTTP((req,res)=>{
  res.set('Access-Control-Allow-Origin', '*');
  return {
    schema: Schema,
    pretty: true,
  }
}));
```

**Comment by Aaike** [comment]
nvm i just figured out i can use the other middleware to enable cors on specific routes :) thx !
