### ISSUE TITLE
Stack traces

### ISSUE THREAD

**Issue by stefk** [graphql/express-graphql#50]
Hi,

To enable stack traces, the documentation recommends to provide an `error => error` function to the `formatError` option. However, like most `GraphQLError` properties, `stack` is not enumerable and therefore not visible when converting the error object to a JSON string .

So currently the only way to get useful info is to implement a custom format function like [this one](https://github.com/graphql/graphql-js/issues/28#issuecomment-187949901). 

Wouldn't it be simpler to make the error details enumerable (stack, nodes, locations, etc.) in `GraphQLError`? If that's not possible, why not providing a common debug function in this package?

**Comment by leebyron** [comment]
Thanks for the report. I changed the Readme to do as you suggest and provide a common custom format function that includes stacks in 458962972baef11a2aa440e1edc989e63e2fbb48.

The reason for making those properties non-enumerable is to ensure against any accidental leaks of information when printing errors which can be a security issue for some. It ensures that any data shown from errors is opt-in.
