### ISSUE TITLE
mention CDN in README

### ISSUE THREAD

**Issue by odigity** [graphql/express-graphql#510]
I was looking at the package.json to learn about dependencies and was surprised to not see graphiql listed, since I know express-graphql can serve graphiql out-of-the-box.

So, I searched the repo and discovered it's served via links to cdn.jsdelivr.net based on a version number hard-coded in the express-graphql source:

    https://github.com/graphql/express-graphql/blob/3412b88186055b275e9da78dc17e501646e9d4c7/src/renderGraphiQL.js#L30
    https://github.com/graphql/express-graphql/blob/3412b88186055b275e9da78dc17e501646e9d4c7/src/renderGraphiQL.js#L80

Given that this may have privacy and reliability implications for some people, I suggest explicitly mentioning this in the README.

**Comment by IvanGoncharov** [comment]
@odigity Thanks raising this issue and sorry for the delay.
I completely removed CDN usage in #524.
