### ISSUE TITLE
can you give me a function for reset the result before return

### ISSUE THREAD

**Issue by lixiang02** [graphql/express-graphql#512]
I want to chang the result before return
but the code no function do it

And, I can't make sure to do that is right, can you ask me? thanks

 
![%IH5H){ASWS2)}FC@OURI_K](https://user-images.githubusercontent.com/11606542/58408705-ee247480-80a0-11e9-8dae-70a7f7bf054e.png)

**Comment by IvanGoncharov** [comment]
@lixiang02 You should not manually change the result of graphql execution since it brakes contract between client and server.
But if you really need to do this you can use `customExecuteFn` option to wrap standard `execute` and apply your custom transformation.
