### ISSUE TITLE
Allow to know when a query has finished being processed

### ISSUE THREAD

**Issue by guigrpa** [graphql/express-graphql#52]
I've seen #36 but my need is far more simple. I'd love to have a way to know when a GraphQL query has finished being processed, so that my custom-built logging library can "close the story" of the request (I'm using hierarchical stories). I'm not interested in the result of the request, not even if it was successful or threw an error, just in the fact that it ended.

I see two ways to accomplish this:

1. The middleware returns its main promise:

    ```coffee
      expressGraphql = require 'express-graphql'
      graphqlMiddleware = expressGraphql (req) ->
        schema: gqlServer.getSchema()
        rootValue: {story: req.logStory}

      expressApp.use '/api/graphql', (req, res) ->
        graphqlMiddleware req, res
        .finally -> req.logStory.close()
    ```

2. The middleware accepts a callback:

    ```coffee
      expressApp.use '/api/graphql', expressGraphql (req) ->
        schema: gqlServer.getSchema()
        rootValue: {story: req.logStory}
        done: -> req.logStory.close()
    ```

I believe the second alternative is better, since it is simpler and doesn't involve leaking the middleware's implementation details (the fact that it uses promises).

I can propose a PR if you find this idea useful.

**Comment by leebyron** [comment]
I like the idea of a logger, but I believe this is the wrong layer of abstraction to add such a thing. Instead this should be a feature of `graphql-js` - there's a task tracking this today at https://github.com/graphql/graphql-js/issues/284

**Comment by guigrpa** [comment]
Agreed, thanks for your reply

**Comment by guigrpa** [comment]
@leebyron In case you might be interested, here's the logger lib (and Chrome extension) I've built and want to integrate with a GraphQL/Relay application in production: http://guigrpa.github.io/storyboard/

![Storyboard](https://github.com/guigrpa/storyboard/blob/master/docs/Storyboard.gif?raw=true)

**Comment by leebyron** [comment]
Very cool!

Closing this in favor of https://github.com/graphql/graphql-js/issues/284
