### ISSUE TITLE
Is 'graphql' not a dependency for this package?

### ISSUE THREAD

**Issue by 3nuc** [graphql/express-graphql#522]
Shouldn't the npm 'graphql' package be a normal dependency rather than a dev dependency for express-graphql? I have to manually do `npm install graphql` or else any call of a 'express-graphql` function throws an error about "graphql" module not found.

**Comment by IvanGoncharov** [comment]
@3nuc It's necessary since you can't duplicate instances of `graphql` so it's required that you manually install single `graphql` to be used by all packages. For more details please read: https://nodejs.org/es/blog/npm/peer-dependencies/
