### ISSUE TITLE
const schema = require('./schema');

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql/express-graphql#554]
I have a sample around that is declared like:

```
...
const schema = require('./schema');
....
app.use('/api/graphql', graphqlHTTP(() => ({ schema, graphiql: true })));
.....
```

This used to work - not for the life of me it will not load.

Just throws:
Error: Cannot find module './schema'

Any help appreciated - thanks!

**Comment by IvanGoncharov** [comment]
@OpenSpacesAndPlaces Don't think it's related to `express-graphql`. 
But you can check if you have `schema.js` in the same folder as file that requires it.
