### ISSUE TITLE
Resolver return only 500 internal server error

### ISSUE THREAD

**Issue by online0227** [graphql/express-graphql#563]
**Login resolver:** 
```
login: (parentValue, { email, password }, req) => {

      AuthService.login({ email, password, req }).then(data => {
        if (data)
          return data;
      }).catch(err => {
        console.log("error in mutation : ")
        console.log(err);
        return err;
      });
    },
```
**It shows correct error response when I put wrong id and password, as follwing:**

> error in mutation : 
> Invalid credentials.

**But in React:**
```
onSubmit({ email, password }) {
    this.props.mutate({
      variables: { email, password },
      refetchQueries: [{ query }]
    })
    .then(data => {
      console.log("data : ")
      console.log(data);
    })
    .catch(err => {
      console.log("error : ")
      console.log(err)
    });
  }
```

**Shows only (in Chrome console):**

> POST http://localhost:3001/graphql 500 (Internal Server Error)
> Error: Network error: Response not successful: Received status code 500

**Following is mutation I run above:**
```
export default gql`
mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    _id
    email
  }
}
`;
```

How can I fix this?
I want react generates same error as it was in graphql resolver.

**Comment by IvanGoncharov** [comment]
@online0227 You need to make `login` nullable if you use SDL you need to remove `!`.
Also, you need to return the promise: `return AuthService.login`
