### ISSUE TITLE
Update GraphiQL to v0.16

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/express-graphql#573]
I can't update GraphiQL past v0.14.
Reproduce:
```
yarn upgrade graphiql --latest
npm start
```
Any help will be greatly appreciated 🤗

**Comment by acao** [comment]
0.17.0 now has a working minified build again
https://unpkg.com/browse/graphiql@0.17.0/graphiql.min.js
^^

more details:
https://github.com/graphql/graphiql/issues/976#issuecomment-558860070
https://www.npmjs.com/package/graphiql/v/0.17.0
https://github.com/graphql/graphiql/releases/tag/graphiql%400.17.0

**Comment by acao** [comment]
I'll create a PR today

**Comment by acao** [comment]
seems the strategy has changed, and now it gets locally bundled with the server on initialization? clever!

so i should just need to bump the GraphiQL version
