### ISSUE TITLE
Inject custom headers to express graphql

### ISSUE THREAD

**Issue by josorioromero** [graphql/express-graphql#579]
Hey everyone, 

I'd like to know how to inject headers when using express graphql. The problem is, if I use multiple instances like this, importing modules to work as a SPA every single header coming from the module get overwritten by the first module I import:

```
app.use('/route1/graphql', expressGraphQL({
    schema: firstSchema,
    graphiql: (process.env.NODE_ENV === 'local' || process.env.NODE_ENV === 'development'),
    formatError: e => AccelerateErrorHandler(e, 'an error')
}));

app.use('/route2/graphql', expressGraphQL({
    schema: secondSchema,
    graphiql: (process.env.NODE_ENV === 'local' || process.env.NODE_ENV === 'development'),
    formatError: e => AccelerateErrorHandler(e, 'an error')
}));
```

So, is there a way to inject headers directly as params in the `expressGraphQL` function?

```
app.use('/route1/graphql', expressGraphQL({
    schema: secondSchema,
    headers (?)...
    graphiql: (process.env.NODE_ENV === 'local' || process.env.NODE_ENV === 'development'),
    formatError: e => AccelerateErrorHandler(e, 'an error')
}));
```

Thanks.

**Comment by acao** [comment]
good question! because you are reusing the same express routes each time to instantiate each middleware, the middlewares will overwrite eachother, so in this example only the third schema will be executable. you may want to read the docs to express app.use(). do you want to combine schemas?

as far as adding headers in express, you can do this via a middleware that uses `res.headers.set()`. make sure this middleware is added before graphql express middleware, as the latter is a terminating middleware and thus it sends response, any middlewares after it will not be executed

**Comment by josorioromero** [comment]
Thanks for the reply @acao 
Yes I need to combine the schemas using one single `app` instance because this is a SPA. I need to add a custom header for every single module to send the module name. Gonna try `res.headers.set()` though.

**Comment by josorioromero** [comment]
update @acao as I need to set the headers in the request, the `res.headers.set()` approach won't work for me

**Comment by acao** [comment]
if you need to set the headers in the request, then it sounds like you need to do that on the client side? if you have some reason otherwise use req.headers.set()

@urigo /the guild have an excellent tool for merging schemas:
https://github.com/Urigo/merge-graphql-schemas

**Comment by josorioromero** [comment]
I did it on the cliend side @acao however, the problem appears when I'm importing the routes as you mentioned above, because `app.use` overwrites the header value. So I thought it could be possible to inject headers directly to `expressGraphQL` in the server.

**Comment by acao** [comment]
I'm sorry but it just doesn't look like you can override inbound request headers, and i'm still not really sure why. if `graphql-express` had a `headers` option it would be for setting response headers, not overriding the inbound request headers.

Maybe you'll find some answers from the express community: https://gitter.im/expressjs/express
