### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by gtamas** [graphql/express-graphql#580]
I have a question about performance.

I've created a simple NodeJS server which supports GrahQL via IBM's OpenAPI-to-GraphQL lib and Express-GraphQL. Just tried to run some basic performance tests and I noticed that there is a huge performance difference between simple REST and GQL calls. 

For example:

REST:

ab -n 1000 -c 100 -k -m GET -T application/json "http://127.0.0.1:3000/api/test"  

Requests per second:    1753.59 [#/sec] (mean)

GQL:

ab -n 1000 -c 100 -k -m GET -T application/json "http://127.0.0.1:3000/graphql?query={test}"

Requests per second:    935.34 [#/sec] (mean)

The "test" endpoint just returns some JSON, there is no DB or any real server-side processing behind it.

I'm using an Express / Loopback 4 server. GraphQL is served via Express-GraphQL middleware. 

My question:

I know this performance loss could be caused by many things. I just want to make sure it's not the middleware. Is this big performance decrease normal? I mean, some slowdown is to be expected, but  It's like 50% worse...

Is there a way to improve performance? Or could this be caused by the OtG lib? I generate GQL schema and resolvers only once, at startup time.

**Comment by acao** [comment]
can you see what happens without the open api to graphql middleware?

**Comment by gtamas** [comment]
@acao  
Thanks for getting back to me.

I tested this, and I don't think it's OtG. 

Here is what I did: 
I replaced the GQL schema generated by OtG with and empty one and then I added a single resolver like so:

```
 const { buildSchema } = require('graphql');
 const request = require('request-promise');
 
// Dummy schema
const schema = buildSchema(`
    type Query {
      test: String
    }
  `);
 
// Simple resolver..
    const root = {
      test: async () => {
        return await request('http://127.0.0.1:3000/api/test');
      },
    };
  
    ....
// Here I add the express-graphql middleware

   this.app.use('/graphql', graphqlHTTP({
       rootValue: root,
       schema
}));
```

So now it's just a basic schema. Yet, AB test produces very similar results as before:

ab -n 1000 -c 100 -k -m GET -T application/json "http://127.0.0.1:3000/graphql?query={test}"

Requests per second:    889.74 - 1000 [#/sec] (mean)

ab -n 1000 -c 100 -k -m GET -T application/json "http://127.0.0.1:3000/api/test"

Requests per second:    1500-1907.29 [#/sec] (mean)

So it seems a bit better but it's still much slower. I guess this makes sense, since with GQL it's actually 2 requests, while querying the API directly is only a single request.

But should it be this much slower? Isn't there some way to improve this?

**Comment by gtamas** [comment]
I guess there might be no way to make this faster. OtG generates similar resolvers too.

Replacing await request('http://127.0.0.1:3000/api/test') with some static string produces much better results, like 2000 req / sec. So it's slow because of the extra requests.
