### ISSUE TITLE
Can't install express-graphql in my project

### ISSUE THREAD

**Issue by levitomer** [graphql/express-graphql#584]
There is an issue while I am trying to `npm install express express-graphql graphql --save`

Log file shows these errors interchangeably on frequent attempts:

**1st attempt:**
```
37 verbose node v10.11.0
38 verbose npm  v6.4.1
39 error code ETARGET
40 error notarget No matching version found for raw-body@^2.4.1
41 error notarget In most cases you or one of your dependencies are requesting
41 error notarget a package version that doesn't exist.
41 error notarget
41 error notarget It was specified as a dependency of 'express-graphql'
42 verbose exit [ 1, true ]
```
**2nd attempt:**
```
155 verbose node v10.11.0
156 verbose npm  v6.4.1
157 error code ETARGET
158 error notarget No matching version found for accepts@^1.3.7
159 error notarget In most cases you or one of your dependencies are requesting
159 error notarget a package version that doesn't exist.
159 error notarget
159 error notarget It was specified as a dependency of 'express-graphql'
160 verbose exit [ 1, true ]

```

**Comment by danielrearden** [comment]
That's normally just a hiccup with the npm registry. Those versions of both packages do exist. If the issue doesn't resolve itself, deleting your `package-lock.json` file may help.

**Comment by SpiffGreen** [comment]
I believe you could force the installation using --force flag on npm

**Comment by Taiwrash** [comment]
I run into this many times and the way out for me most time is by installing ```express-graphql``` first before installing the ```graphql``` package itself.

### Solution 1
```bash
npm i express-graphql graphql --save
```
### Solution 2
```bash
npm i express-graphql --save
```
then
```bash
npm i graphql --save
```

This solved this issue every time for me.
