### ISSUE TITLE
Readme Refers to `customFormatErrorFn`, but Actual Function Seems to be `formatError`

### ISSUE THREAD

**Issue by machineghost** [graphql/express-graphql#588]
The readme.md documentation talks about `customFormatErrorFn`, but that option didn't work for me at all.  However, I discovered the (much better named) `formatError` option, and it worked great, so it seems the documentation is just behind.

I would submit a PR but I'm not 100% certain I'm correct about the above (I just know `formatError` worked for me and `customFormatErrorFn` didn't).

**Comment by IvanGoncharov** [comment]
@machineghost What version of library you are using?
Can you please post the output of `npm ls express-graphql`?

**Comment by machineghost** [comment]
└── express-graphql@0.5.4 

Guess I need to update this repo; sorry!
