### ISSUE TITLE
Incompatible with graphql-js 0.5.0-beta

### ISSUE THREAD

**Issue by JohnyDays** [graphql/express-graphql#59]
Trying to test the new graphql beta release, but doesn't look like express-graphql supports the breaking changes. I've debugged as far as identifying that https://github.com/graphql/express-graphql/blob/master/src/index.js#L183 isn't taking into account the new context argument, is that everything that would be needed?

**Comment by leebyron** [comment]
Yes, #57 is fixing this, we'll have it into a release within the next day or two.

**Comment by JohnyDays** [comment]
Cool! I'll try it out
