### ISSUE TITLE
Using extensions to modified results object

### ISSUE THREAD

**Issue by carlosmarte** [graphql/express-graphql#592]
I’m working on a project that has structured and unstructured data. Some downstream system is updated through a JSON editors were teams can add and remove fields. This is counterintuitive and problematic because GraphQL enforces types. At the current moment my work around is to stringify the object and assign it to a primitive type (String) in my GraphQL schema. 

I just realized that within the extensions function I can modify the results object before the response is sent. 

Question: is this by design and will you continue to support this? Or will modifying the results object from within extensions function be consider a (use at your own risk) hack? Because this function may change in the future or results may become immutable.

**Comment by danielrearden** [comment]
A `formatResponse` option may be added in the near future that would probably be better suitable for your use case. For unstructured data, you might also consider utilizing a custom scalar, like this [JSON scalar](https://github.com/Urigo/graphql-scalars#json) from `graphql-scalars`.
