### ISSUE TITLE
Easy way to log queries?

### ISSUE THREAD

**Issue by dandv** [graphql/express-graphql#596]
I tried to log queries as described in [this SQ question](https://stackoverflow.com/questions/41142471/log-all-graphql-responses-with-express),

```js
function loggingMiddleware(req, res, next) {
  if (req.url.startsWith('/graphql')) {
    winston.debug('REQUEST: ', req.body);
  }
  next();
}
app.use(loggingMiddleware);
```

Problem is, `request.body` is always undefined. I'm sending POST queries from graphiql.

On the other had, would it not make sense to make the query available in the [`extensions`](https://github.com/graphql/express-graphql#providing-extensions), since the `variables` and `result` are available there as well?

**Comment by danielrearden** [comment]
That information is already available. The `extensions` function is passed a `RequestInfo` object with the following properties:

```
/**
 * All information about a GraphQL request.
 */
export type RequestInfo = {|
  /**
   * The parsed GraphQL document.
   */
  document: ?DocumentNode,

  /**
   * The variable values used at runtime.
   */
  variables: ?{ +[name: string]: mixed, ... },

  /**
   * The (optional) operation name requested.
   */
  operationName: ?string,

  /**
   * The result of executing the operation.
   */
  result: ?ExecutionResult,

  /**
   * A value to pass as the context to the graphql() function.
   */
  context?: ?mixed,
|};
```

The `document` is the parsed GraphQL [document](http://spec.graphql.org/June2018/#sec-Language.Document) that was sent to the server. You can convert this back to a string using the `print` function from the core library:

```
const { print } = require('graphql')

const documentString = print(document)
```

Documents may include more than one operation, in which case a valid request will also include the `operationName` to indicate which operation should be executed. If you only want to print that specific operation, you can use `getOperationAST`:

```
const { print, getOperationAST } = require('graphql')

const operation = getOperationAST(document, operationName)
const operationString = print(operation)
```
