### ISSUE TITLE
TypeError: expressGraphQL is not a function

### ISSUE THREAD

**Issue by RaghavK16** [graphql/express-graphql#667]
**Import in the server.js file:**
`const expressGraphQL = require('express-graphql')
`
**While using the app.use function as follows:**

```
app.use('/graphql', expressGraphQL({
  schema: schema,
  graphiql: true
}));
```

**I'm getting an error:** TypeError: expressGraphQL is not a function

Is it a package dependency issue?

**Comment by danielrearden** [comment]
Please import the middleware like this as shown in the README:

```
const { graphqlHTTP } = require('express-graphql`)

app.use('/graphql', graphqlHTTP({
  schema: schema,
  graphiql: true
}));
```

If you don't want to use destructuring, then you can do something like 

```
const expressGraphQL = require('express-graphql`)

app.use('/graphql', expressGraphQL.graphqlHTTP({
  schema: schema,
  graphiql: true
}));
```

**Comment by RaghavK16** [comment]
Thanks, appreciate it a lot.
