### ISSUE TITLE
Curious why getting URLSearchParams is not defined from express graphql

### ISSUE THREAD

**Issue by xarvey** [graphql/express-graphql#685]
I was trying to follow the instruction and setup https://graphql.org/graphql-js/running-an-express-graphql-server/ When running node server.js and tried to open localhost:8080/graphql

I got an error message {"errors":[{"message":"URLSearchParams is not defined"}]}

I dug into the node a bit and found https://github.com/graphql/express-graphql/blob/master/src/index.ts#L469 is the place the code stops executing.

Wondering if there are any workarounds, I'm using chrome so it shouldn't be a browser compatibility issue.

Thanks in advance.

**Comment by danielrearden** [comment]
URLSearchParams was added as a global in Node 10. Please make sure you are using a version of Node that's compatible with the library.

**Comment by xarvey** [comment]
Thank you so much, that's exactly the problem.

⇒  node --version
v9.11.1
