### ISSUE TITLE
graphiql: Uncaught TypeError: React.render is not a function

### ISSUE THREAD

**Issue by mloncaric** [graphql/express-graphql#69]
It looks like React.render was removed.

**Comment by Freezystem** [comment]
+1

**Comment by mloncaric** [comment]
Which version are you using? They've fixed the problem in 0.5.1 - https://github.com/graphql/express-graphql/releases/tag/v0.5.1

**Comment by Freezystem** [comment]
I was using v0.5.0. thx it's working properly now.
