### ISSUE TITLE
Does context in express-graphql work differently from Apollo-server?

### ISSUE THREAD

**Issue by LunaticMuch** [graphql/express-graphql#721]
I am wondering if the context in express-graphql works differently from the apollo-server implementation. I've been working with a piece of code, originally based on apollo-server, and ported to express. 

I replaced the apollo with express and express-graphql on a [fork](https://github.com/LunaticMuch/graphql-music/tree/express-graphql) and made it running. No changes to the previous context definition. 

When I run a query, like the following:

```graphql
{
  songs(name: "bella ciao") {
    artist {
      name
    }
  }
}
```

I get an error

```
"message": "Cannot read property 'iTunes' of undefined",
```

I have the suspect the context, which in the original code with apollo was an object, cannot work in the same way in express, thus requires a different approach.

**Comment by danielrearden** [comment]
`context` should be an object that will be made directly accessible to your resolvers. You can pass in a function, but that function will not be called by `express-graphql`. Just pass in a plain object instead.

**Comment by LunaticMuch** [comment]
Thanks for confirming. I know how the context work, in theory, but I cannot explain so why it does not work. As you said, because the context is just passed to the resolver, if the context function/object is correct, it has to work on both apollo and express-graphql. Actually, it does not.

**Comment by danielrearden** [comment]
My point is that, unlike with Apollo Server, you can pass a function to context in `express-graphql`, which is what you are doing:
```
const context = () => {
  const connectors = createConnectors();
  const loaders = {
    artist: new DataLoader((IDs) =>
      Promise.resolve(
        IDs.map((id) => connectors.iTunes.artist({ id })),
        console.log(`Dataloader here for ${IDs}`)
      )
    ),
  };

  return { connectors, loaders };
};
```

The correct way to do this, with minimal changes to your code, would be something like:

```
app.use(
  "/graphql",
  (req, res, next) => graphqlHTTP({
    schema: schemaWithResolvers,
    context: context(), // <-- notice we are calling your function and just passing in a plain object
    graphiql: true,
  })(req, res, next)
);
```

**Comment by Yaojian** [comment]
```
app.use(
  "/graphql",
  (req, res, next) => graphqlHTTP({
    schema: schemaWithResolvers,
    context: context(), // <-- notice we are calling your function and just passing in a plain object
    graphiql: true,
  })(req, res, next)
);
```
TypeScript fails in compiling the last `(req, res, next)` with message
```
TS2554: Expected 2 arguments, but got 3.
```
 because [the Middleware is defined](https://github.com/graphql/express-graphql/blob/2882357145b8ee131c23e7745649cb2fe9911ca1/src/index.ts#L183) as
```
type Middleware = (request: Request, response: Response) => Promise<void>;
```

Is this a bug? @danielrearden

**Comment by danielrearden** [comment]
The middleware does not currently utilize the `next` parameter, as indicated by the type for `Middleware`. So omit the parameter and only pass in `req` and `res`.
