### ISSUE TITLE
Publish new version of express-graphql

### ISSUE THREAD

**Issue by andrehsu** [graphql/express-graphql#734]
@IvanGoncharov, is it possible to release a new version of express-graphql containing all the latest commits? Specifically, I want to use the features implemented in PR #696.

**Comment by acao** [comment]
I can look into that today!

**Comment by acao** [comment]
I don't have permissions for this project on npm, perhaps @IvanGoncharov or @brianwarner can help me with this?

**Comment by acao** [comment]
@andrehsu we have reverted this PR as it diverges from the transport spec. if you would like to have different error response codes, you'll want to take that up with the graphql-over-http transport spec WG!

**Comment by andrehsu** [comment]
@acao I've read the GraphQL Over HTTP spec, and I don't understand why the commit was reverted. 

Right now, the status code is always `500` for errors, when more appropriate status codes might be `400` for malformed requests, `401` for unauthenticated requests, `429` for too many requests, etc.

If you [read here](https://github.com/graphql/graphql-over-http/blob/master/spec/GraphQLOverHTTP.md#status-codes), the spec doesn't preclude this, it just says that a successful response MUST be `2xx`, and it SHOULD be `200`.

Could you please clarify your interpretation of the spec and why that precludes `handleRuntimeQueryErrorFn` from setting the status code to `4xx` codes?
