### ISSUE TITLE
GraphiQL allow sending HTTP headers within this project implementation.

### ISSUE THREAD

**Issue by vieks** [graphql/express-graphql#74]
How can I send custom headers from the GraphiQL client ?

On every client REST APIs it's possible to define headers for the HTTP requests. How can I do the same with this project ?

An API client (GraphiQL) without the possibility to set headers but only the data ? Really ? I can understand GraphiQL is network protocole agnostic when installed as a standalone, but not in the context of this lib ! Indeed **express-graphql** means **http-graphql**.

On GraphiQL there is a "Query variables" sections so why not adding a "HTTP headers" section too ?
It's a serious need for many of us.

PS: Please don't tell me to install directly the GraphiQL from this repo [graphql/graphiql](https://github.com/graphql/graphiql) ... while precisely the purpose of express-graphql is to have an easy and ready to use package preventing to bother with installing each other libs as a standalone.

**Comment by leebyron** [comment]
Unfortunately this is not currently possible. Indeed the correct solution if you need to provide a custom implementation of GraphiQL is to configure that version yourself.

You should not have to install from the graphiql repo though, there is a simpler way - in fact this package also does not depend directly on that repo, instead it uses the CDN cached versions of typical GraphiQL.

https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js

---

If you have thoughts on how to enable what you're looking for, I'm definitely open to considering a pull request.

**Comment by antoinealej** [comment]
Hi Vieks,

On Chrome, you can download some extensions to mock your header. I used ModHeader and it's working pretty well.

Cheers!
