### ISSUE TITLE
create new release?

### ISSUE THREAD

**Issue by cowboyd** [graphql/express-graphql#747]
It looks like the last release was 5 months ago, and there is lots of goodies contained on master that aren't on npm, including much better support for subscriptions. Is there anything holding back?

**Comment by acao** [comment]
@cowboyd we are waiting on graphql 16 to release support for subscriptions and stream/defer.

**Comment by cowboyd** [comment]
Thanks @acao,

For anybody else arriving here, more information on the `@defer` and `@stream` directives https://foundation.graphql.org/news/2020/12/08/improving-latency-with-defer-and-stream-directives/

**Comment by justinmchase** [comment]
You're waiting? Does it mean that this code doesn't actually work?
https://github.com/graphql/express-graphql#setup-with-subscription-support

What timeline are we looking at here?
