### ISSUE TITLE
graphql apollo client v3 CORS error

### ISSUE THREAD

**Issue by Loki2** [graphql/express-graphql#751]
Access to fetch at 'http://www.server.api/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://192.168.100.25:3000/' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by acao** [comment]
@Loki2 you must configure your express server to accept cross origin requests! The cors module will take care of that. If you have any other issues, the express.js support community can help!
