### ISSUE TITLE
Interoperability with graphql go

### ISSUE THREAD

**Issue by flovilmart** [graphql/express-graphql#767]
[GraphQL Go](https://github.com/graphql-go/graphql/blob/1a9db8859ef57c2821bbd47b0db9a1a09e617f41/graphql.go#L29) will always default the operation name to an empty string which causes this server to fail serving requests.

The bottom value is expected to be `null` and not `''` in this project.

Would it be acceptable that we change the implementation in this project to allow `operationName: ''` being interpreted as running the default operation?

The alternatives are:
- when using the go, always specify the operationName (cumbersome)
- updating the `graphql-go/graphql` project to allow operationName being nullable.

Would be happy to provide a PR with relevant tests.

**Comment by acao** [comment]
I think this makes a lot of sense! `operationName` with an empty string value of `''` would just require an additional check for `operationName.length > 0`, and should be treated as an anonymous operation.

**Comment by flovilmart** [comment]
Perfect! Let me take some time to fix it up!

**Comment by flovilmart** [comment]
@acao I opened the above PR; let me know if there’s anything else I can do to help

**Comment by flovilmart** [comment]
ping @acao ?

**Comment by IvanGoncharov** [comment]
Closing since it should be resolved in `graphql-go`, see https://github.com/graphql/express-graphql/pull/768#issuecomment-933028222
