### ISSUE TITLE
Add NPM documentation

### ISSUE THREAD

**Issue by hanumanjiblog** [graphql/express-graphql#770]
PleaseAdd documentation in npm website, in npm website show blank.
![Screenshot_20210804-005113](https://user-images.githubusercontent.com/87318222/128073713-f3fdc765-3e8d-48fc-acf9-e2d4ca6ac11f.png)

**Comment by notrab** [comment]
@hanumanjiblog there is, perhaps there was something wrong with NPM at the time you tried to view it.

![CleanShot 2021-08-18 at 19 44 28@2x](https://user-images.githubusercontent.com/950181/129954498-7e7a2554-1385-41bb-a266-4ad8e0513aeb.png)
