### ISSUE TITLE
Peer dependency error on new installation of graphql

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [graphql/express-graphql#805]
I am getting this:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: graphql-first@1.0.0
npm WARN Found: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^14.7.0 || ^15.3.0" from express-graphql@0.12.0npm WARN   node_modules/express-graphql
npm WARN     express-graphql@"^0.12.0" from the root project
npm WARN   1 more (the root project)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^14.7.0 || ^15.3.0" from express-graphql@0.12.0  
npm WARN node_modules/express-graphql
npm WARN   express-graphql@"^0.12.0" from the root project
```

**Comment by dk-raw** [comment]
There are people having the same issue since 2018! This is unacceptable!

**Comment by 1catchman** [comment]
Same issue, I had to install it with `--force` flag

**Comment by adam-nielsen** [comment]
As a temporary workaround you can run `npm install` with the `--legacy-peer-deps` option.

Looks like the same issue as #790.

**Comment by hamidjavadi** [comment]
Please upgrade GraphQL package to latest version => 16.5.0
Thanks

**Comment by newbeb** [comment]
FYI, Looks like they are deprecating express-graphql in favor of graphql-http: https://github.com/graphql/express-graphql/pull/816.

**Comment by amerikan** [comment]
From the various graphql servers alternatives, in our experience the easiest one to migrate over to, almost a drop in replacement, was [GraphQL Yoga](https://www.the-guild.dev/graphql/yoga-server) with their [Express integration](https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-express).

**Comment by saihaj** [comment]
this project is deprecated and we recommend to moving to alternatives. You can read more here https://github.com/graphql/express-graphql#this-library-is-deprecated
