### ISSUE TITLE
How to put the request body into context?

### ISSUE THREAD

**Issue by kennetpostigo** [graphql/express-graphql#91]
I'm currently attempting to get the request body into `context`, because part of the body contains a JWT that needs to be decoded. However when I try the following I get `undefined` for `context`:

```js
app.use('/', graphqlHTTP((req) => ({
  schema: Schema,
  context: req.body,
  pretty: true,
  graphiql: false
})));
```
I logged out `req` and I didn't see `body` in there. I'm using a [react-reach](http://github.com/kennetpostigo/react-reach), and adding the following to the `body` on the request:

```js
{
  query: {...},
  queryParams: {...},
  options: {
    token: '...'
  }
}
```

I know the `body` is being interpreted because my queries/mutations that are in the body are being interpreted and executed. Just can't seem to find it when passed to `context`.

**Comment by yss14** [comment]
How did you solved this?

**Comment by alanraso** [comment]
Same [question](https://stackoverflow.com/questions/37331238/how-to-pass-request-body-into-graphql-context) on SO
